### ISSUE TITLE
Implement withEmailPasswordAuth wrapper 

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#111]
Like https://reactrouter.com/web/api/withRouter

That way, instead of doing:

```js
import {EmailPasswordAuth} from "supertokens-auth-react/recipe/emailpassword";

class App extends React.Components {
    render() {
        return (
            <EmailPasswordAuth>
                 <Dashboard />
            </EmailPasswordAuth>
        );
    }
}
```

One can do:

```js
import {withEmailPasswordAuth} from "supertokens-auth-react/recipe/emailpassword";

class Dashboard extends React.Components {
    render() {
        return (
              // Always need a session to access this component.
        );
    }
}

export default withEmailPasswordAuth(Dashboard);
```

And 

```js
import {EmailPasswordAuth} from "supertokens-auth-react/recipe/emailpassword";

class App extends React.Components {
    render() {
        return (
                 <Dashboard />
        );
    }
}
```
Making sure that the Dashboard component is never used without authentication being applied.

**Comment by rishabhpoddar** [comment]
Makes sense! This seems to be a better approach!

**Comment by NkxxkN** [comment]
Discussed on call. 

We are going to stay with the first method "EmailPasswordAuth" components for the following reasons:
 - We want to keep one method only for consistency in the app
 - We would have to implement a singleton because otherwise all components would call `isEmailVerified` at the same time which is sub optimal.
 - How do you manage overwriting props such as `doesSessionExist` or `onShowEmailVerificationScreen` with the `withEmailPasswordAuth` approach?
