### ISSUE TITLE
Add prefix to illustration classNames or use `data-supertokens` attribute

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#112]
The className used for illustration could clash with user defined CSS.

We are adding className attributes to any element that can be overwritten by users in `SuperTokens.init()`. See "How To" => https://supertokens.io/docs/emailpassword/common-customizations/styling/changing-style

```js
        <button type="submit" css={styles.button} className="button">
        </button>
```

Will be rendered as:

```js
       <button type="submit" class="button react-shadow-rnqgtj-Button">SIGN UP</button>
```

In the example above, the issue is that if the user defines `.button` in their CSS, it will clash with ours, even though we did not intend to use this `button` css.

In order to fix, we can simply put our illustration className in `data-supertokens` attribute.

```js
        <button type="submit" css={styles.button} data-supertokens="button">
        </button>
```

We will need to modify the docs in https://supertokens.io/docs/emailpassword/common-customizations/styling/changing-style.

**Comment by rishabhpoddar** [comment]
- Doesn't the shadow-root help with the issue of clashing `.button` class?
- If we do the above, do we need the shadow-root anymore?
- I thought emotion would add some prefix to all class names.. if it's not doing that, why are we using it?

**Comment by NkxxkN** [comment]
> Doesn't the shadow-root help with the issue of clashing .button class? 

Yes no problem with shadow-root. But we could also easily prevent it from happening without shadow Dom.

> If we do the above, do we need the shadow-root anymore?

Yes. Because shadow-root also prevents general html tags clashing. Without shadow-root, we don't have a nice way to prevent that.

> I thought emotion would add some prefix to all class names..

Emotion does randomize css classes (see `react-shadow-rnqgtj-Button` from above).
The issue with that is: how do we let users know the name of the style they can overwrite?
So I initially fixed that issue by adding empty indicators `className`. But now I realise that it will probably become a problem when people have disabled shadow-root. So the new fix is to move these indicators to `data-supertokens` attributes to make sure it does not clash.

In the docs we can replace with 
![image](https://user-images.githubusercontent.com/5072452/103992747-dfff6b00-5194-11eb-9cfe-18f04bfa7f8b.png)


>  if it's not doing that, why are we using it?

Emotion helps with randomising css classes but it also helps with declaring media queries, hover states, disabled states, and css animations from within react JSX tags directly.

**Comment by rishabhpoddar** [comment]
Alright! I don't think I understand these concepts very well. So if you are confident about these changes, please go ahead..

**Comment by NkxxkN** [comment]
To summarise the impact of this change:
 - No breaking change.
 - Prevent css clashes
 - Simply needs a tiny docs change
