### ISSUE TITLE
Call Send Email on successful signup from EmailVerification feature when required mode is enabled

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#114]
Alternative way to fix https://github.com/supertokens/supertokens-node/issues/67

**Comment by rishabhpoddar** [comment]
Do you mean call the send email API on load of the /verify-email component? Because we need to send the email whenver that page is loaded, not just if sign up is success and that page is loaded.

**Comment by NkxxkN** [comment]
Why would we call the API every time on page load?
We would send a lot of unsolicited emails if someone simply refreshes the page, or if they try to access an authenticated part of the app and get redirected to the page, or if they open their browser and restore pages, etc...

It feels suboptimal to do such a thing. 

A better design would be to send the email once on sign up and then to send it only when "Resend email" is clicked.
