### ISSUE TITLE
Use backend custom callback createAndSendCustomEmail for testing

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#116]
Store reset password link / email verification link in cookies during tests instead of sending email in order to be able to test  valid tokens.

**Comment by rishabhpoddar** [comment]
If you want, you can start the node process in test mode like `TEST_MODE=testing node index.js` in your tests. This will prevent the actual email from sending, and everything else will work the same.

**Comment by NkxxkN** [comment]
Nice! I will do that too. Thanks.

**Comment by rishabhpoddar** [comment]
If this is irrelevant, please close this issue

**Comment by NkxxkN** [comment]
Still relevant. We are not testing email verification / reset password with valid tokens at the moment since we can't access a valid token. But using the createAndSendCustomEmail we will be able to do so.
