### ISSUE TITLE
Cleanup user facing functions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#117]
I am starting to feel the need to cleanup may of the user facing functions we provide. Examples are:
- The user will need to implement `doesSessionExist` in several places if they need to implement it.
- If a user needs to customise the requests sent to their backend layer in someway (same change for all requests), they will need to implement several callbacks as well..

I strong think we should solve the above (and more?) problems in a cleaner way to reduce the complexity of docs + maintainance .

**Comment by NkxxkN** [comment]
Agreed! 

**Another example:** 
Redirections are a bit messy if you decide to disable the default implementation. Example of what I had to do with `supertokens-react-themes` to support redirection post signup to verify email screen:
https://github.com/supertokens/supertokens-react-themes/pull/4/files#diff-c9144b1d3ece0a6c801620489d6b8454cdedb6184a450c11827e7b36bb6a2c29R15

**Yet another example:**
I once came up with this snippet for a user who wanted to overwrite how the form looked like:

```
const formStyles = {
  style: {
    row: {
      width: "85%",
      maxWidth: "362px",
    },
  }
};

SuperTokens.init({
  appInfo: {...},
  recipeList: [EmailPassword.init({
    signInAndUpFeature: {
      signInForm: {
        ...formStyles
      },
      signUpForm: {
        ...formStyles
      }
    },
    resetPasswordUsingTokenFeature: {
      enterEmailForm: {
        ...formStyles
      },
      submitNewPasswordForm: {
        ...formStyles
      }
    }
  }), Session.init()],
});
```

Maybe related to https://github.com/supertokens/supertokens-auth-react/issues/86

**Comment by NkxxkN** [comment]
- If we think that: "Nobody is going to use SuperTokens react without using its backend", should we depreciate all API related props?
 
 - `doesSessionExist` should always use Session recipe's doesSessionExist method. If someone wants to overwrite doesSessionExist, it's because they want to use their own session management. Then they should overwrite the whole Session Recipe and provide their own?
 
 - `onHandleSuccess`: Should we have one onHandleSuccess only in EmailPassword configs?
 
 
Using feature props means you need to add the component yourself and disable default implementation. This shouldn't be encouraged.

**Comment by NkxxkN** [comment]
Regarding styling, I don't see the need for a separation between the different screens. 
If a user wants to change how a button looks like, they will want to change it for all pages.
we should have just one `theme` attribute.

**Before**

```
const formStyles = {
  style: {
    row: {
      width: "85%",
      maxWidth: "362px",
    },
  }
};

SuperTokens.init({
  appInfo: {...},
  recipeList: [EmailPassword.init({
    signInAndUpFeature: {
      signInForm: {
        ...formStyles
      },
      signUpForm: {
        ...formStyles
      }
    },
    resetPasswordUsingTokenFeature: {
      enterEmailForm: {
        ...formStyles
      },
      submitNewPasswordForm: {
        ...formStyles
      }
    }
  }), Session.init()],
});
```


**After**

```
SuperTokens.init({
  appInfo: {...},
  recipeList: [EmailPassword.init({
       theme: {
           row: {
               width: "85%",
               maxWidth: "362px",
           }
       }
  }), Session.init()],
});
```

**Comment by rishabhpoddar** [comment]
> If we think that: "Nobody is going to use SuperTokens react without using its backend", should we depreciate all API related props? We can add a preAPIHook with a context, same way as we do for onHandleSuccess for changes that they want to apply to all API requests.

Yea. We should do this.

> doesSessionExist should always use Session recipe's doesSessionExist method. If someone wants to overwrite doesSessionExist, it's because they want to use their own session management. Then they should overwrite the whole Session Recipe and provide their own?

Yes. I think for now, we should forget that people will provide their own session implementation. Will make things more simple.

> onHandleSuccess: Should we have one onHandleSuccess only in EmailPassword configs?

Not sure. There are different scenarios here.. but we can have one, which takes the context, thereby simplifying things perhaps?

> Regarding styling, I don't see the need for a separation between the different screens.

Agreed. But that's why we have the pallette object right? I still think being able to customise styles per screen is useful.

**Comment by NkxxkN** [comment]
> Not sure. There are different scenarios here.. but we can have one, which takes the context, thereby simplifying things perhaps?

What are the different scenarios you are describing?

I think we should not keep maintaining two different methods as it defeats the purpose of this cleanup.

**Comment by NkxxkN** [comment]
Another thing we should make more consistent is our way to redirect to some parts of the app. We have a `onSuccessRedirectURL` in the configs that we use anytime we need to redirect to the app:
  - on successful signup/signin.
  - when going to `/auth` and a session already exists
  - After email is verified and user clicks on "Continue" button.
  
We also have:
  - `onHandleForgotPasswordClicked` props for `SignInAndUp` feature for when a user clicks on "forgot Password" link.
  - `onHandleShowEmailVerificationScreen` props to `EmailPasswordAuth` to redirect to email verification screen.


We are not handling well: 
  - Redirect to the correct login path (if not `/auth`) from EmailPasswordAuth when no session.
  - Redirect to the correct login path (if not `/auth`) from EmailVerification after click on "Continue" when token is expired and no session.
  
![image](https://user-images.githubusercontent.com/5072452/104435788-140bcf00-558d-11eb-86be-36a5d6bdef4f.png)

We should have generic methods in the EmailPassword Init directly to make sure we keep consistency and we do not have to add them as props to all components feature as we keep adding new components that interact with each others.

Sub issue: https://github.com/supertokens/supertokens-auth-react/issues/121

**Comment by NkxxkN** [comment]
API File refactoring:
- API file take recipeInstance as a parameter, no need for rid or signUpAPI, removing all API functions from EmailPassword recipe manager.

- Remove General error type.
- Define API return types in place.
