### ISSUE TITLE
Implement Router methods

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#12]
### With React route
```jsx
import {SuperTokensRoute} from "supertokens-auth-react"

<Router history={history}>
   <NavBar />
      <Switch>
         <SuperTokensRoute />
      </Switch>
   <Footer />
</Router>
```
### Reach Router ? 
- [] TODO  @NkxxkN make researches, decide wether we should support reach router on not. https://reach.tech/router/

### Manual routing
```jsx
import SuperTokens from "supertokens-auth-react"

if (SuperTokens.canHandleRoute()) {
   return SuperTokens.getRoutingComponent()
}
```

- Internally `SuperTokensRoute` uses `SuperTokens.getRoutingComponent()`

**Comment by NkxxkN** [comment]
**Updates**

So `<SuperTokensRoute> ` did not work out as expected because of how `react-dom-router` works.
Its behaviour is weird but it basically allows for routes to be nested in components but only once... 

```js
<Switch>
  <Route path="/route1">
  <div><Route exact path="/route2"></div>
  <Route exact path="/route3">
</Switch>
```
In here, only `/route1` and `/route2` will work. `/route3` is omitted.

So with our `SuperTokensRoute` component:

```js
<Switch>
  <Route exact path="/route1">
  <SuperTokensRoute/>
  <Route exact path="/route2">
</Switch>
```
Only `/route1` and `SuperTokensRoute` would work. `/route2` would be omitted. 

We can not afford to do that as we can not force people to add `SuperTokensRoute` at the end of their `Switch` component.
The reason for that is that people are catching all routes to the last component by doing:
```js
<Switch>
  <Route exact path="/route1">
  <SuperTokensRoute/>
  <Route path="/">
</Switch>
```
Notice that `<Route path="/">` does not contain the key word `exact`, which means that it will catch all routes that starts with `/`.


So the fix for this is to not have nested routes at all. To do this, we can not use a wrapper component (such as SuperTokensRoute), but we need to call a method from the Switch component:

```js

import {getSuperTokensRoutesForReactDomRouter} from 'supertokens-auth-react';

<Switch>
  <Route exact path="/route1">
  {getSuperTokensRoutesForReactDomRouter()}
  <Route exact path="/route2">
 <Route path="/">
</Switch>
```

That way, no routes are ignored, and you can keep catching all routes at the end of the Switch.

@rishabhpoddar ^ some implementation changes worth taking a look at for you.

**Comment by rishabhpoddar** [comment]
@NkxxkN thanks! I think `getSuperTokensRoutesForReactDomRouter` works just fine :)

**Comment by rishabhpoddar** [comment]
Actually, one problem I see with this approach is that we will have to add this router as a dependency in our project. Now there are four ways to do this:
- As a `peerDependency`: This will ensure that they do not get two versions of `react-dom-router`, which is ideal. But they need to have it, otherwise, our function will fail.
- As a `dependency`, with a specific version: This means that there is a risk of them having two versions of this in their project.
- As a `dependency`, with the version as `*`: I am not sure, but maybe this means that if they already have it, npm doesn't download the latest version (or does it?). If they don't have it, then npm will download the latest one and so the node process will not throw an error on start.
- We add it as a `peerDependency`, and use `require` instead of `import` for this. Here, we will use `require` inside the `getSuperTokensRoutesForReactDomRouter` function. So if they don't call it, then it will not be required and the node process will not crash on start (i think).

So I prefer the last option - if it works. If it doesn't then I prefer option number 3. But I'm confident that the last option will work.

**Comment by NkxxkN** [comment]
So, I found an elegant way to bring back our `<SuperTokensRoute>` component. 

It is said in "react-dom-router" docs that all element within a `Switch` must be `Route`. But multiple `Switch` are allowed within a `Router` (preferably on top since we only use exact Route matches, but that's up to the user)

That fixes our issue by letting users import `<SuperTokensRoute>` from anywhere within their `<Router>` component.


I'm also using React.lazy to load `react-router-dom`, which allows us to set `react-router-dom` as a peer dependency as you mentioned in your preferred solution.
I verified that an app without `react-router-dom` does not throw any error if the `SuperTokensRoute` component is not loaded.

The only disadvantage with this solution is that we can not export `SuperTokensRoute` from the package directly.

So 

```js
import SuperTokens, {SuperTokensRoute} from "supertokens-auth-react"
```
becomes:

```js
import SuperTokens from "supertokens-auth-react";
import SuperTokensRoute from "supertokens-auth-react/components/SuperTokensRoute";
```

**Comment by rishabhpoddar** [comment]
I prefer that the user doesn't have to import from another path like the above. It adds more scopes for mistakes.

- What do other libraries that work with `react-router-dom` do?
- Worst case, I still prefer using the function call method over the import from a different path method. But we can discuss this.

**Comment by NkxxkN** [comment]
Auth0: they do not have to catch routes with react dom router this since their Auth0Provider redirects to the subdomain. Their wrapper is checking if there is a user, and redirecting to their login subdomain.
 Here is the only example mentioning react-router-dom: https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md, but it's not to take control of routes.

I have no clue what keycloak is doing their code makes no sense to me :/ 

I tried to github dork for projects using react-router-dom but couldn't find any that had our use case. Did you have any project in mind I could dig in?

We can move back to using the method, but I didn't check yet if `require()` from inside the method would work. So I'll dig into this now.

**Comment by NkxxkN** [comment]
Regarding wether we should support reach router and react router, I found this article from the creators of both routers https://reacttraining.com/blog/reach-react-router-future/ 

Reach is a lightweight version of react-router which use the new react API. They will be merged together in next release.

I suggest that we only support react-router for 2.6 and we might add support for reach in future releases.

**Comment by rishabhpoddar** [comment]
> Did you have any project in mind I could dig in?

I don't. Sorry.

> We can move back to using the method, but I didn't check yet if require() from inside the method would work. So I'll dig into this now.

Alright!

> I suggest that we only support react-router for 2.6 and we might add support for reach in future releases.

Cool.

**Comment by NkxxkN** [comment]
I tried to move back to `getSuperTokensRoutesForReactDomRouter` method. The issue is that as soon as you load anything from `supertokens-auth-react`, if `react-router-dom` is not in the main project, it will throw an error even though I require the package from inside the method. 

That means that any "optional" dependencies can not be loaded from the main package. 

We will have to import the `SuperTokensRoute` component from another, isolated file, if we'd like to keep `react-router-dom` in `peerDependencies`.

```js
import SuperTokens from "supertokens-auth-react";
import SuperTokensRoute from "supertokens-auth-react/SuperTokensRoute";
```

Should we move on with this? @rishabhpoddar

**Comment by rishabhpoddar** [comment]
I am surprised that you can't check if a node module exists without loading it. Have you tried [this approach](https://stackoverflow.com/a/15303236/3867175).

As a side note, please make sure not to have any `import` / `require` statements for `react-router-dom` outside that function.

**Comment by NkxxkN** [comment]
Nice catch! It's working well. 
Moving back to 
```js
import SuperTokens, {getSuperTokensRoutesForReactDomRouter} from 'supertokens-auth-react';
```

**Comment by NkxxkN** [comment]
Small difference between the version without router and the version with react-router-dom:

 react-router-dom matches routes based on the pathname and not the combination of pathname + query params.
That means we will match a route even though the recipe Id is unknown. In that case, we have two choices:
 - render nothing (i.e. unknown component) in current implementation.
 - render the first one that matches.

(anyway, this is very edge case so both work imo)

What do you think is best? @rishabhpoddar 

See https://github.com/supertokens/supertokens-auth-react/pull/11/files#diff-cb70d48ffe3b5c6df3235d8da1c91cfae355dc0233469677848b14567109b668R27 for implementation details.

**Comment by rishabhpoddar** [comment]
@NkxxkN , I prefer rendering the first one that matches. I think this is already mentioned in the routing algorithm you had written? Am I misunderstanding something?
