### ISSUE TITLE
React styles Vs styling library (aphrodite)

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#13]
React allows to add styles directly to its components using the `style` props.
Nevertheless, some styling libraries are becoming very popular to do styling in react. Styled components and [aphrodite](https://github.com/Khan/aphrodite) coming first.

- Pros of using React:
  - no need for external dependencies.

Pros of using an external lib:
  - Support for mouse events (:hover, :visited) and others (:after :before)
  - Support for media query resizing ("@media (max-width: 440px)")
  - Use classes (semi randomised) instead of polluting the dom with style attributes (inspecting the code looks much nicer
  - Integrated merging of styles (default + user provided styles)
 
Cons: 
  - lightweight library but still a dependency (but it helps us to get rid of another dependency => shadow root)
  
I think we should go with Aphrodite because after exploring react styling for an hour or so, I realised that it is too restrictive and we would need to add a stylesheet at some point (for media query particularly).

  Shadow root does not prevent from propagating the CSS from parent to child, it only works the other way around, making sure that 3rd party styling does not clash with parent styling. We don't have any good way to prevent parent style to clash with our modules. Shadow-root helps to isolate an inserted stylesheet but if we only use randomised classes with aphrodite we do not need to isolate our component with a shadow root.

**Comment by NkxxkN** [comment]
@rishabhpoddar ^ let me know what you think

**Comment by rishabhpoddar** [comment]
I prefer:
- aphrodite
- Shadow-root + reset CSS

**Comment by NkxxkN** [comment]
So it seems that only the background colour gets propagated from parent to child with react shadow root but not the tags styles like h1,h2,h3 etc.. I'm so confused!

So that means as long as we set our background colour our code should be isolated. The problem now is that aphrodite does not work anymore with shadow-root because the style is not propagated down to the shadow root element (the stylesheet is added in the parent element). But reactShadow integrates with [Emotion](https://emotion.sh/docs/object-styles) which seems to be doing the exact same thing as aphrodite.

So we could go with:
  - React shadow-root, no need for reset CSS
  - Emotion

**Comment by rishabhpoddar** [comment]
I suggest that we should get full clarity on the behaviour of shadow-root first before choosing what else to use with it. Only the background colour being propagated doesn't seem to make sense to me..

**Comment by NkxxkN** [comment]
**I confirm that Shadow DOM is protected from outside CSS, and elements from the parents are protected from shadow DOM CSS.**
The clearest thing I found on shadow dom https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/. Docs from Mozilla are really unclear.

I suppose that html doesn't have `white` background by default so it just renders its content with a transparent layout. That's what confused me.

**Comment by rishabhpoddar** [comment]
Fair enough. So the final solution is:
- Shadow-dom
- Emotion

Is the above correct?

**Comment by NkxxkN** [comment]
Yes, going with shadow-dom + emotion. That means we are now compiling with babel but type checking with typescript beforehands.

**Comment by rishabhpoddar** [comment]
> That means we are now compiling with babel but type checking with typescript beforehands.

Cool. Please be sure to make changes to `npm` scripts, `.npmignore` file, git pre commit script (I think).
