### ISSUE TITLE
Peer dependency versions

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#14]
This issue is intended as a tracker on which versions we will support for our peer dependencies.

- `react`: Currently `^16.14.0` but we can definitely go down as this is the latest version that was installed when I ran `npm install react`

- `react-router-dom`: Currently `^5.2.0` which is latest. I think we could support up to `4.0` since the API never changes. I'll have to test.

**Comment by rishabhpoddar** [comment]
Normally, I like to specify just the minimum version like `>=16.14.0`.
