### ISSUE TITLE
Email verification screen not showing with Blitz JS

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#140]
- Blitz.js uses nextJS. 
- The sign up / in UI works, but after sign up, it fails to redirect to the email verification screen.
- When manually navgiating to `/auth/verify-email?rid=emailpassword`, that screen seems to load.

Is this a blitz specific issue? or is this a nextJS specific issue?

**Comment by NkxxkN** [comment]
Fixed in `0.5.0`
