### ISSUE TITLE
Third Party Recipe Module (frontend)

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#154]
### Recipe Module

```js
import ThirdParty from "supertokens-auth-react/recipe/thirdparty";

Supertokens.init({
   appInfo: {},
   recipeList: [{
       ThirdParty.init({
            preAPIHook?: (context: ThirdPartyPreAPIHookContext) => Promise<RequestInit>;
            getRedirectionURL?: (context: ThirdPartyGetRedirectionURLContext) => Promise<string | undefined>;
            onHandleEvent?: (context: ThirdPartyOnHandleEventContext) => void;
            useShadowDom?: boolean; // Default to true.
            palette?: Record<string, string>,
            emailVerificationFeature: {
                 style?: // Same as EmailPassword.
                 disabledDefaultImplementation?: boolean; // Default to false.
                 mode: "REQUIRED" | "OFF", // default to "OFF"
            },
            signInAndUpFeature: {
                 disabledDefaultImplementation?: boolean; // Default to false.
                 style?: Record<string, CSSObject>,
                 providers: [
	            ThirdParty.Google({
                        buttonComponent?: Element
                    }),
                    {
                        id: string,
                        name: string,
                        buttonComponent?: Element
                     }
               ]
            } 
   }]
});

// Same as EmailPassword without SIGN_UP => we only use SIGN_IN.
export type ThirdPartyPreAPIHookContext {
  action: "VERIFY_EMAIL" | "SEND_VERIFY_EMAIL" | "IS_EMAIL_VERIFIED" | "SIGN_IN" | "GET_AUTHORISATION_URL";
  requestInit: RequestInit;
}
```

**Config normalisation:**
- `disableDefaultImplementation`: Only disables `/auth` route. Can't disable `/auth/callback/{thirdPartyId}`.
- `providers`: Throw an error if empty or `length === 0`.

### Feature

```js
<SignInAndUp>
```

No props given. Use configs.

### Theme

```js
<SignInAndUp>
   <SignInAndUpTheme
      // Provided by the above SignInAndUp feature.
      providers: [{
        id: string,
        buttonComponent: Element
      }],
      signInAndUpClick(id: string) => void
      privacyPolicyLink?: string
      termsOfServiceLink?: string
   />
</SignInAndUp>
```

##Logic flow

#### IF route is `/auth?rid=thirdparty` ⇒ Show `SignInAndUp` UI
- If a session already exists, redirect to  `{action: "SUCCESS" }`.
- If `error` queryParams is present, display the general error.
- Render all providers connect button (in the order provided in configs)
- Click on one provider => https://github.com/supertokens/frontend-driver-interface/blob/master/v1.6.0.md#get-oauth-authorisation-url
   - Create `state`(See section below)
   - Store in sessionStorage
   - Redirect to `url` from above request
   

#### IF route is `/auth/callback/{thirdPartyId}`**

**Routing**:
       - If no state params, or if state is present and does not match any result => set `recipeId = null` , hence, using the first matching recipe feature.
       - If state params is present in session storage, use associated `rid`.
       
**In the `SignInAndUp` feature component:**
   1/ Show Loading screen
   2/ If `thirdPartyId` not in configs => redirect to `{action: "SIGN_IN_AND_UP" }, { error: "error"}`
   3/ Getting the `state` param from URL. Compare it with the sessionStorage value:
         - If no match => redirect to `{action: "SIGN_IN_AND_UP"}, { error: "error"}` (i.e. `/auth?rid=thirdparty&error=error`)
         - If match => extract the `redirectToPath` from it.
   4/ Getting the `code` param from the URL query params
        - If no `code` ⇒ redirect to `{action: "SIGN_IN_AND_UP"}, { error: "error"}` (i.e. `/auth?rid=thirdparty&error=error`)
        - If `code` : Use https://github.com/supertokens/frontend-driver-interface/blob/master/v1.6.0.md#signinup-api with: 
        ```json
          {
                thirdPartyId: string,
                code: string,
                requiresEmail: false
            }
        ```
           - On `status: "OK"` ⇒ redirect to `{action: "SUCCESS"}, {redirectToPath} `
           - On error => redirect to `{action: "SIGN_IN_AND_UP"}, { error: "error"}` (i.e. `/auth?rid=thirdparty&error=error`)

            
  ### State management

- The state will be a generated nonce. which we will store in the session storage with a prefix. `supertokens-oauth-state`.
- The nonce is generated on the frontend, and is used as a state queryParams on the authorisation URL.
- The state is stored in session storage.
    - After verifying the state, we remove it.
    - If verification fails, we still remove the state.
    - The key for the state will be the `supertokens-oauth-state`. The value will be 
    ```
    {
       redirectToPath?: string,
       state: string,
       expiresAt: timestamp,
       thirdPartyId: string,
       rid: string
    }
    ```
    
### Generate random nonce:

Based on https://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid algorithm to generate random uuid, it is not recommended to use Math.random for cryptographic quality. A better implementation uses `crypto` which is available browser side.

Replacing algorithm for uuidv4 generation: 
```js
function uuidv4() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}
```

With: 

```js
function getRandomState() {
      return (`${1e15}`).replace(/[018]/g, c =>
        (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
      );
  }
```
will give results such as: `50f0dab62c7c5f89` and follows 

This method is defined as: 

> The Crypto.getRandomValues() method lets you get cryptographically strong random values. The array given as the parameter is filled with random numbers (random in its cryptographic meaning).
getRandomValues() is the only member of the Crypto interface which can be used from an insecure context.

and is available in all browsers.

Also from Chrome developer blog: https://v8.dev/blog/math-random

> The Web Cryptography API introduces window.crypto.getRandomValues, a method that returns cryptographically secure random values, at a performance cost.

## Design
https://github.com/supertokens/supertokens-core/issues/181

**Comment by NkxxkN** [comment]
Question related to state management:
Should we store the above values in the session storage but only send the nonce in the state?
that way we make sure to never encounter `414 Request-URI Too Large` HTML Errors which can happen when the URL is too long.

**Comment by rishabhpoddar** [comment]
- I'm not sure that `Record<string, CSSObject>` is the right type to use. a user should be able to give an object like `{textColor: "", padding: "", ...}`. I think I had seen `Record` being used somewhere else as well in the code, which may cause usage issues..
-  `emailVerificationMode` must be inside the `emailVerificationFeature` just like in `emailpassword` recipe? This object should also contain everything else that the emailpassword recipe has (in its emailVerificationFeature block)
- Shouldn't the feature component be called something like `ThirdPartyFeature` instead of `ThirdPartyConnect` (like how we have in the other recipe)?
- Logic flow needs to consider that an error needs to be shown in the login UI in case of callback failure.
- Logic flow in either of the paths needs to check if a session exists before doing anything else
- In the callback logic, if thirdPartyId not in configs, why are we not redirecting to `{action: "SIGN_IN_AND_UP"}, { error: "error"}`? That is, why are we not showing an error in the login screen?
- Logic for callback needs to check that the `rid` in the state belongs to this recipe. If not, then it should try and find the right recipe.. this means that before anything is done (even before checking if a session exists), we must check the `rid` in the state. Also, i don't think that we need to verify the state as such in this step (as that is anyway done after the routing has picked a recipe). This is a special case for the routing algorithm. 
- Generate random nonce: -> I would recommend seeing how other providers do this.
- What are the props that need to be given to the feature component?
- What are the props that are given to the theme component by the feature component?
- The configs in the init should be scoped inside a feature block (just like how it's done for emailpassword recipe)
-------

> Should we store the above values in the session storage but only send the nonce in the state?

This makes sense, but I wonder why other providers do not do this..

**Comment by NkxxkN** [comment]
>I'm not sure that Record<string, CSSObject> is the right type to use. a user should be able to give an object like {textColor: "", padding: "", ...}. I think I had seen Record being used somewhere else as well in the code, which may cause usage issues..

A CSSObject is equivalent to : 

```
{color: "", padding: "", ...}
```

So a Record<string, CSSObject> is:

```
{
    button: {
      color: blue,
      margin: ...
    },
    container: {},
    title: {}
    ...
}
```

> Shouldn't the feature component be called something like ThirdPartyFeature instead of ThirdPartyConnect (like how we have in the other recipe)?

For EmailPassword recipe we have `SignInAndUp`, `ResetPasswordUsingToken`. We do not need to add `Feature` at the end of the name of the component.
For ThirdParty, my thought process was that since we are going to allow to connect to third party post signin, it would not be named `SignInAndUp`. But looking at the designs, it is really tied to "Sign Up / Sign In".
Should this be named `SignInAndUp` (`ThirdParty.SignInAndUp`) when including the TOS and "Sign Up / Sign In" title? And it would include a "sub feature" containing only the buttons? which we would call `Connect` (`ThirdParty.Connect`)?

**Comment by NkxxkN** [comment]
> - Generate random nonce: -> I would recommend seeing how other providers do this.

It is usually done server side.
Here next-auth is using node `crypto` lib.  (`crypto.randomBytes(32).toString('hex')`)  https://github.com/nextauthjs/next-auth/blob/6c5db3c2a02feb33711a52b4c6c4645f6c7004f0/src/server/lib/csrf-token-handler.js#L37

`randomBytes` is random enough for creating csrf. We do not have access to `randomBytes` method on the front end so the equivalent is the above `crypto.getRandomValues` We can add randomness going from 15 to 30 characters for the sake of it.

Storing state in session/local storage?  Vs in cookies?
Session/Local storage means we are vulnerable to stealing CSRF if our customers have any XSS injections PRE sign in. Escalating an XSS to full account takeover.
Should we prevent this by storing the state value in the cookies? Under which domain? `websiteDomain`? Does that work for multi tenancy scenarios?

> This makes sense, but I wonder why other providers do not do this..

This is what auth0 does actually: https://auth0.com/docs/protocols/state-parameters#redirect-users

**Comment by rishabhpoddar** [comment]
Using cookies on the frontend will not prevent theft of the state via XSS attacks since the frontned has to read the state anyway, which means the cookie cannot be httpOnly. We could generate the state on the bakcned, store them in httpOnly cookie, and then send those to the backend for verification, but then if an XSS attack is happening, the attacker would probably just steal the auth code directly from the frontend. Hence, doing it via the backend is also not really safeguiarding the situation.

**Comment by NkxxkN** [comment]
`if an XSS attack is happening, the attacker would probably just steal the auth code directly from the frontend`
 
**In case of a reflected XSS attack** in the sign in page (using a get param), the xss would be triggered only pre sign in. It would not run on callback, hence it's impossible to steal the code.

**In case of a stored XSS attack** in the sign in page (which is less likely to happen), then I suppose that the attacker could steal the code, throw an error, and use that code for themselves, whatever we do to mitigate.

Another OAuth CSRF attacks goal can be to link your Twitter account to your victim's credentials. That way you can use Twitter to signin and get connected to your victim's account. 
That means the attack is not about stealing a `code`, but about maliciously giving your code to the victim. in that case, a reflected XSS is enough, as an attacker could overwrite the sessionStorage with the state the want before our SDK verifies it.

That being said, we are not vulnerable to this since we are not doing any account consolidation (yet).

**Comment by rishabhpoddar** [comment]
TODO: Should we use session storage or local storage to store state? The main issue may be that with mobile devices may not properly support session storage.

**Comment by NkxxkN** [comment]
Let's use session storage as it reduces the scope of the state to one tab only. Make sure we test properly on any device, browsers (especially app's embedded browsers, i.e. messenger/twitter etc...). And decide later if we have to change.

**Comment by rishabhpoddar** [comment]
@NkxxkN please confirm that all points in my comment above have been considered in addition to this point: We need an auth wrapper for this recipe as well (just like we have in emailpassword), that will redirect users in case a session does not exist or email is on and is not verified.

**Comment by NkxxkN** [comment]
All points have been answered/added to the first comment of this issue.

For Auth wrapper, yes we need one. 
It seems to me that the logic would be exactly the same. It's based on `Session` and `EmailVerification` recipes. I don't think it really makes any sense to have this live in both `EmailPassword` and `ThirdParty`. And yet another one in the future in `ThirdPartyEmailPassword`.

That `Auth` component should move either to a higher level `SuperTokens.Auth`, or to the `Session` recipe (`Session.Auth`) ?

**Comment by rishabhpoddar** [comment]
> And yet another one in the future in ThirdPartyEmailPassword.

That is OK. 

> That Auth component should move either to a higher level SuperTokens.Auth, or to the Session recipe (Session.Auth) ?

I prefer not moving it to higher level. I would be OK with sessions, if this did not do email verification redirects too.. but it does. If you want, you can extract the main logic into some component that is shared across all recipes, and use that, but from a user's point of view, I prefer if it's kept within the recipe itself.

**Comment by NkxxkN** [comment]
**Update on state management:**

I prefer using `supertokens-thridparty-state` as opposed to `supertokens-state-{nonce}`. 

1/ We use state from session storage to find the recipe id for routing. There is a higher chance of not finding the object in the session storage if we add randomness to it. By using a fixed key, we increase our chances of finding the right key, and get routing done properly. It allows for better separation of concerns as the recipe feature is responsible for state comparison, not the routing.

2/ By using a fixed key, we do not pollute the session storage.
