### ISSUE TITLE
Email Verification as a recipe

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#159]
# In progress

## Description 

 Extract the logic for email verification from EmailPassword recipe to its own recipe.

## Config unchanged

Recipe is created under the hood in the EmailPassword constructor.

## Implementation

- [x] Create an `AuthRecipeModule abstract RecipeModule` which implements:
   - abstract `signOut` method.
   - getRedirectURL hook config.
   - Redirection mechanism (previously in RecipeModule)
   - Use `authRecipe` from within `EmailVerification` recipe whenever the EmailVerification needs to perform actions such as `redirect` or `signOut`.

- [x] Init `EmailVerification` from `EmailPassword` configs when mode is required. Give EmailPassword instance as an `authRecipe` attribute to EmailVerification. 

- [x] Remove email verification routes from `getFeature` in `EmailPassword` recipe. 

- [x] Move `EmailVerification` feature to its own folder.

- [x] Move `EmailVerification` theme to its own folder.

- [x] Extract styleContext to be shared between recipes.
   -  Add a `rawPalette` props instead of using `EmailPassword.getConfig().palette`.

- [x] Extract assets to the components folder.
- [x] Move FDI methods related to `EmailVerification` from `EmailPassword`.

**Comment by rishabhpoddar** [comment]
Will the `EmailVerification.init()` not take any options?

**Comment by NkxxkN** [comment]
Configs stay unchanged. Recipe is created under the hood by the EmailPassword recipe.
Updating in the main description ^
