### ISSUE TITLE
What is someone decides to have multiple sign up pages?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#18]
Is your code architected in a way to allow:
- Yours to have multiple sign up pages?
   - One default, rest custom
   - All custom
- Same as above, but for sign in

**Comment by NkxxkN** [comment]
All of the above are possible. 
You can easy create a `/custom` route overriding the default theme, giving it new styles and new methods directly in the props.
See what is done here: 
https://github.com/supertokens/supertokens-auth-react/blob/feature-email-password/test/react-test-app/src/AppWithReactDomRouter.js#L32

Both default and custom co exist. The props are not changed at all at the moment but can be.

**Comment by rishabhpoddar** [comment]
Nice! I'm closing this issue then. Feel free to reopen to discuss this more.

**Comment by NkxxkN** [comment]
Since we actually have singleton pattern, having multiple signIn signUp that behave differently, for example different APIs (partners.example.com, users.example.com) would not work right?

**Comment by rishabhpoddar** [comment]
Singleton means that we have a single instance of the recipe. This implies that the config for all the sign up/in pages will be the same. This means the styling, `apiDomain` etc.. will be the same.

However, that will be true for "one instance" of the react app. If `partners.example.com` is another react app compared to `users.example.com`, then it would still work. Or even if they are the same react app, but not an SPA (across these domains), it would still work.

The problem would come if you have one login UI at `example.com/auth/user` and another at `example.com/auth/partners`, and if they are within the same react app.

The way this could be solved is if the user creates two (parent) recipes based on the `emailpassword` recipe. The recipeId would still be the same of the child recipes (`email-password`), but their `websiteBasePath` would be different. This would work fine, excepting that we would need to do routing based on the path first, and then based on the `recipeId` - which I think you are already doing?

On the backend, they would have to give the `websiteDomain` as `""` and give us the function to generate the reset password URL based on the user.

**Comment by NkxxkN** [comment]
> but their websiteBasePath would be different. This would work fine, excepting that we would need to do routing based on the path first, and then based on the recipeId - which I think you are already doing?

Yes path first, then recipeId.
Cool so it should work out of the box. Closing
