### ISSUE TITLE
In UI only demo we do not need an extra `recipe` query param since rid is already there.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#188]
So we can also just do init for both, thirdparty and emailpassword recipe within supertokens.init and the routing of the SDK should take care of displaying the right UI?

**Comment by NkxxkN** [comment]
In `for-tests` app we need it to tests for different routing scenarios.
One with only EmailPassword initialised. 
One with ThirdParty. 
One with both.

In `with-typescript` example that's true. We can init both and use rid params.

In the demo repo, we'll have two branches to make it easier for users to copy/paste configs for their use case.

Does that make sense?

**Comment by NkxxkN** [comment]
Closing as it is solved in `with-typescript` example.
