### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#2]
- for local dev
- setup circleci testing

**Comment by NkxxkN** [comment]
I'm pretty psyched about https://storybook.js.org/ for our testing. 
If implemented fully, it could ultimately serve as a reference for documentation and help users to customise widgets.
Wdyt?

**Comment by rishabhpoddar** [comment]
I am not familiar with https://storybook.js.org/. I couldn't gauge much from their site either, however, I am open to using anything. So if you think this is awesome, we shall do that :)
