### ISSUE TITLE
Remove warning of Can't resolve 'react-router-dom' in '/Users/ghandal/Personal/marketplace/node_modules/supertokens-auth-react/lib/build

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#220]
This happens even if `useReactRouterDom:false` is set.

**Comment by codefingas** [comment]
@rishabhpoddar how do I reproduce this?

**Comment by rishabhpoddar** [comment]
@codefingas if you create a project that does not use react-router-dom and uses supertokens, when you run this on a browser, you will see this error in the browser console.

**Comment by codefingas** [comment]
@rishabhpoddar okay thanks.

**Comment by gusfune** [comment]
I had this same issue on nextJS, fixed temporarily by adding `react-router-dom` as a dependency on the project. Not ideal, but suppresses the warning for now.

**Comment by rishabhpoddar** [comment]
@gusfune this issue has been solved. Please upgrade to version 0.12.0 of the supertokens-auth-react lib. You can also get rid of the `useReactRouterDom: false` config setting in the frontend config.
