### ISSUE TITLE
Add lint check and prettier to examples folder as well

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#231]

**Comment by codefingas** [comment]
@rishabhpoddar will this be for all the recipes within examples?
- for-tests
- with-blitz
etc

**Comment by rishabhpoddar** [comment]
@codefingas this will be for all examples in the example folder. Thanks

**Comment by rishabhpoddar** [comment]
Commit: https://github.com/supertokens/supertokens-auth-react/commit/b0808cb9635f4bd895ad2b4506c61ecd584f0bd1
