### ISSUE TITLE
Update package.json with npm packages instead of github

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#24]
- [x] In `package.json`
Replace  
```
 "supertokens-website": "git+https://github.com/supertokens/supertokens-website.git#5.0" 
```

- [ ] In `test/server/package.json`
Replace 
```
"supertokens-node": "git+https://github.com/supertokens/supertokens-node.git#3.0"
```
with npm package.

**Comment by rishabhpoddar** [comment]
The `supertokens-node` does not need to be replaced cause it's going to be manually installed in CICD anyway. So just `supertokens-website`.

**Comment by NkxxkN** [comment]
Done for supertokens-website
