### ISSUE TITLE
Forms lose style if peer dependency is updated

### ISSUE THREAD

**Issue by gusfune** [supertokens/supertokens-auth-react#248]
This is a follow-up on #246 which I have managed to properly replicate after a few tests. It seems a newer version of @emotion (probably @emotion/react@11.4.0) has a breaking change that avoids the rendering of super tokens components. This also conflicts with any other plugin that is using @emotion on a newer version, causing the following console warning:

`You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

Using:
- supertokens-auth-react: 0.12.1
- supertokens-node: 5.0.1
- supertokens-website: 7.0.1   

<img width="376" alt="Screen Shot 2021-05-10 at 17 39 30" src="https://user-images.githubusercontent.com/1147240/117687619-42568f80-b1b8-11eb-99e8-7c1463e55ef3.png">

**Comment by rishabhpoddar** [comment]
Thanks for the issue. Do you think simply updating the emotion version that we use is a good fix? Cause what if this same issue happens in the future with a newer version of emotion? Any ideas on how we can permanently fix this problem?

**Comment by rishabhpoddar** [comment]
In a test app, I installed the latest version of `@hookform/devtools` and `react-hook-form`, and added the `DevTool` component like so:
```js

render() {
const { register, control, handleSubmit } = useForm({
        mode: "onChange",
});

return (
        <>
           <Router>
             ...
           </Router>
           <DevTool control={control} />
        </>
    );
}

```

I do get the warning you mentioned:
```
You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
```

However, the form still loads correctly for me:
<img width="1280" alt="Screenshot 2021-05-12 at 21 15 37" src="https://user-images.githubusercontent.com/2976287/118005035-a53a5900-b367-11eb-8614-3c01071c3efb.png">

What am I missing so that I can replicate this issue?

**Comment by gusfune** [comment]
We are using yarn `2.x` instead of npm or yarn classic, and we use deduplicate as well to keep only the most recent version of a package. That might be influencing the issue. I did one more test and if I try to use yarn in pnp mode, the same issue happens no matter if I updated other packages using the same dependencies.

**Comment by rishabhpoddar** [comment]
@gusfune I think the above PR should fix this issue - we have added `^` to all the dependencies (including emotion), which will prevent the duplicate warning from coming, and perhaps fix this issue. You can test if it works by using `"supertokens-auth-react": "supertokens/supertokens-auth-react#0.13",` in your packege.json file.

**Comment by rishabhpoddar** [comment]
The new version of this repo (0.13.0) should fix this issue - or at least the duplication warning issue. Closing this for now, but feel free to reopen in case it's not fixed.
