### ISSUE TITLE
Redirect to lowercased URL after successful auth

### ISSUE THREAD

**Issue by olhapi** [supertokens/supertokens-auth-react#252]
@rishabhpoddar hello 👋
I have a case sensitive IDs in my app and it become an issue after adding supertokens auth.

Here's my scenario:
1) User come to some internal website URL (specific movie for example, *website.com/movie/aAAAa123*)
2) That page is protected with supertokens auth., so user will be redirected to auth page *website.com/auth*
3) After successful auth, supertokens redirects user to previous page, but URL will be lowercased *website.com/movie/aaaaa123*
4) User gets 404 error because IDs are case sensitive and there are no such ID.

**Comment by rishabhpoddar** [comment]
@olhapi this issue has been fixed and has been released in v0.13.1
