### ISSUE TITLE
Firefox issue with routing 

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#28]
Steps to reproduce:
1/ Go to `/auth/reset-password`
2/ Component is not displayed.

**Comment by NkxxkN** [comment]
Found the bug:

Issue comes from this line:
https://github.com/supertokens/supertokens-auth-react/blob/0.0/lib/ts/components/superTokensRoute.tsx#L39

This is so strange!

- In firefox: 
```
["a", "aa", "aaa"].sort(a => a.length)
 =>  [ "aaa", "aa", "a" ]
```

- In chrome, safari, opera:
```
["a", "aa", "aaa"].sort(a => a.length)
 => ["a", "aa", "aaa"]
```

Replacing with 

`.sort((a,b) => b.length - a.length)` works well in all browsers.

**Comment by rishabhpoddar** [comment]
I believe there is another place where you are sorting.. something like `"-x.length"`. Please see that too.
