### ISSUE TITLE
Run lint, tests and build checks on Pull Requests

### ISSUE THREAD

**Issue by dulowski-marek** [supertokens/supertokens-auth-react#285]
### Problem
Currently, we are relying on running all the tests, checks and build process on local machine. It is validated when `./addDevTag` is executed, which happens on a release branch `X.Y`. This allows for merging untested and not built changes.

### Idea
1. We can mark `master` and `X.Y` release branches protected.
2. We can prepare a CircleCI configuration, that would run all necessary checks and tests whenever PR is made to a protected branch. This includes release branches in format `X.Y` or `master` branch.

### Advantages
- This will speed up the development. Currently running E2E tests takes minutes, before we are certain we can push a change. This can easily happen in parallel, even for a quicker unit tests.
- This will allow checking code metrics later, test coverage for example.
- This will ensure that `master` and version branches cannot have untested changes.
- This will prevent from pushing directly to protected branches, which enforces code reviews.
- This can give other developers the input useful for working together at a task.
- This will unify the environment the tests are run at. In future it can also run in parallel for multiple different environments (for e2e tests, a browser/OS matrix), elliminating the need for manual tests.

**Comment by rishabhpoddar** [comment]
This makes sense! However, there is an issue that if the current version being worked on depends on a backend SDK version that has not yet been released (due to FDI spec changes), then the tests for the current version will always fail.

How would we solve this issue? - One way is to run only unit tests and not e2e tests when we push a commit. We run e2e tests only when a dev tag is added. However, would doing this actually solve the problem you are trying to solve?

**Comment by dulowski-marek** [comment]
> However, there is an issue that if the current version being worked on depends on a backend SDK version that has not yet been released (due to FDI spec changes), then the tests for the current version will always fail.

This is expected, because you cannot technically release something, that depends on not released SDK. Also, why would we wait for releasing SDK, if it has been implemented? (I'm not saying it's pointless, I can see some reasons but I'm looking for your input).

To my knowledge, we could use Docker to run some version of the SDK and core. If we do it, we may choose a version we run current tests against by specifying an image tag. Then, we may produce a dev image tag for SDK/core image and run tests against it.

**Comment by rishabhpoddar** [comment]
Not going for now. Closing.
