### ISSUE TITLE
Infinite redirect loop when using ThirdPartyEmailPasswordAuth context

### ISSUE THREAD

**Issue by olhapi** [supertokens/supertokens-auth-react#302]
@rishabhpoddar Hello. After wrapping my react app with ThirdPartyEmailPasswordAuth (for access to context) I started getting an infinite redirect to `/auth`. After removing ThirdPartyEmailPasswordAuth wrapper around app everything works as expected, but I need ThirdPartyEmailPasswordAuth to access userId and jwtpayload.

I'm thinking that these conflicting components may be the issue:
import { ThirdPartyEmailPasswordAuth } from 'supertokens-auth-react/recipe/thirdpartyemailpassword';
import ThirdPartyEmailPassword from 'supertokens-auth-react/recipe/thirdpartyemailpassword';

I'm using first to add [context](https://supertokens.io/docs/thirdpartyemailpassword/common-customizations/sessions/user-information-front-end) and second one to add protected [page](https://supertokens.io/docs/thirdpartyemailpassword/nextjs/protecting-route) as per docs.

### My stack:
"next": "^11.0.1",
"supertokens-auth-react": "^0.15.3",
"supertokens-node": "^6.0.4",

### Recipe:
thirdpartyemailpassword

**Comment by rishabhpoddar** [comment]
@olhapi I see. We will work on fixing this issue, in the meantime, can you please try wrapper your whole app in `SessionAuth` instead like:
```
import {SessionAuth} from "supertokens-auth-react/recipe/session";

<SessionAuth>
   <App />
</SessionAuth>
```

This too will provide the same Session context that your app can use, but should not cause infinite redirection.

**Comment by rishabhpoddar** [comment]
Also, you may want to try using `<ThirdPartyEmailPasswordAuth requireAuth={false}>`. By default, this component will redirect the user if not logged in, unless you give it `requireAuth={false}`.

Even if the above works, I would still suggest that you use `SessionAuth` if you want to wrap your whole app in it.

**Comment by rishabhpoddar** [comment]
I am closing this issue since the above should fix the problem you stated. In case it's still there, please feel free to repoen. Thanks

**Comment by olhapi** [comment]
@rishabhpoddar yep, that fixed the issue and I still got user info from the session context. Thx 🙌
