### ISSUE TITLE
getInstanceOrThrow is not defined when using vite and tsc

### ISSUE THREAD

**Issue by tdfirth** [supertokens/supertokens-auth-react#334]
I am using vite to build my project. Works fine in dev mode but a production build leads to the following runtime error:

```TypeError: cd.default.getInstanceOrThrow is not a function```

There is a minimal repo to recreate the error here:

https://github.com/tdfirth/supertokens-debug

To replicate simply run:

```
npm build && npm serve
```

Notes from discord discussion:

> So it doesn't get to the part where it'd use reactRouterDom it tries to call cd.default.getInstanceOrThrow which is undefined, while cd.default.default.getInstanceOrThrow is defined (and points to the right thing)
> The strange part is the default.default part, because it looks like it was wrapped twice for some reason. I tried a quick search to see if it was a bug in the bundler, but nothing came up.

> Yeah, so I've found the problem: we have a circular dependency (which is bad, but worked so far), and the interaction between vite build and our tsc output goes wrong... (I can provide more details if you are interested).
> I'll try and come up with a quick solution tomorrow, it's likely that we can solve this by publishing es modules as well (although removing circular deps would be better).

**Comment by rishabhpoddar** [comment]
Need to be done for:
- [x] supertokens-website
- [ ] supertokens-auth-react
- [ ] supertokens-react-native

**Comment by rishabhpoddar** [comment]
We have released a new version of the supertokens-auth-react SDK (v0.17.4) that removes any circular dependencies that should solve this issue. 

Closing this for now, but feel free to reopen it if needed.
