### ISSUE TITLE
Show Sign up or Sign In by default

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#35]
By default the "Sign In" page is displayed.

![image](https://user-images.githubusercontent.com/5072452/98949160-9e857300-24f7-11eb-834e-df3366aaf096.png)

Should we:
 - keep it as it is (login first which is what most people do)
 - default to sign up (which is good to increase conversion for start ups)
 - allow the user to decide by adding a config:
```js
EmailPassword.init({
   signInAndUpFeature: {
      defaultToSignIn: true
   }
})
```

Another thing to take into account is:
People might want to post/tweet/email links to their signup page, so if we keep the "Sign-In" page, we should have a way to add a query param to toggle to Sign-up.

**Comment by NkxxkN** [comment]
@makerboiAdi wdyt?

**Comment by rishabhpoddar** [comment]
I think we should have the config option, and show sign in by default (since most people do that). If we have the query param, communicating that will be hard.. So not sure about that.

**Comment by makerboiAdi** [comment]
Agreed with @rishabhpoddar. Default to signup with the config option. No need for query param

**Comment by NkxxkN** [comment]
TODO: 
- [ ] Implementation #72 
- [ ] Doc update in `/auth-react` to add config.
- [ ] Update all docs screenshots showing sign in by sign up:
     - [ ] Front end starter guide
     - [ ] Sign up about
     - [ ] Maybe others?
