### ISSUE TITLE
Material-UI component has no styling inside overriden component.

### ISSUE THREAD

**Issue by web-smith** [supertokens/supertokens-auth-react#355]
Somehow material-ui components has no styling applied.

I am using `override.components` property from `ThirdPartyEmailPassword` recipe to replace part of the forms to custom components. Custom component body includes `material-ui` components.

I made [codesanbox](https://codesandbox.io/s/xenodochial-cohen-r85nx?file=/src/App.js:0-1375) as reproduction.

I am not sure if this belongs here or in material-ui package. I am using 4.x material-ui version.

**Comment by rishabhpoddar** [comment]
Hi @web-smith ,
You need to pass `useShadowDom: false` in the `ThirdPartyEmailPassword.init({` function call, and it works. You can do this like:
```js
ThirdPartyEmailPassword.init({
      useShadowDom: false,
      override: {...}
},
```
