### ISSUE TITLE
Allow override of SuperTokensBranding

### ISSUE THREAD

**Issue by jeremylynch** [supertokens/supertokens-auth-react#363]
I am unable to override the SuperTokensBranding component. I have followed the documentation on [React component override](https://supertokens.io/docs/passwordless/advanced-customizations/react-component-override/usage) which has not worked. I would like to remove the _"Powered by SuperTokens"_ footer. 

```js
export let frontendConfig = () => {
  return {
    appInfo,
    recipeList: [
      Passwordless.init({
        contactMethod: "EMAIL",
        override: {
          components: {
            SuperTokensBranding: ({ DefaultComponent, ...props }) => {
              return (
                <p>hi</p>
              );
            },
          }
        }
      }),
      SessionReact.init(),
    ],
  }
}
```

**Comment by rishabhpoddar** [comment]
@porcellus could you please help out with this?

**Comment by porcellus** [comment]
`SuperTokensBranding` is not an overrideable component, you can remove it using CSS. See [here](https://supertokens.io/docs/passwordless/common-customizations/styling/changing-style).

```jsx
export let frontendConfig = () => {
  return {
    appInfo,
    recipeList: [
      Passwordless.init({
        contactMethod: "EMAIL",
        style: {
            superTokensBranding: {
                display: "none",
            }
        }
      }),
      SessionReact.init(),
    ],
  }
}
```
