### ISSUE TITLE
Forgot password routing bug

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#39]
This happens when I use manual routing only.
- [ ] When clicking on "Forgot password", it still shows the sign in form, even though the path is `/auth/reset-password`.
- [ ] When the path is changed to `/auth/reset-password`, it should also contain the `rid`. In general, whenever we navgiate to a page controlled by us (from a button controlled by us), we want to add the `rid`. For example, in case of forgot password, we want to add the `rid` to the route if they have not provided the `resetPasswordURL` in the `signInForm` object during init.

**Comment by NkxxkN** [comment]
Right! 
I forgot about this!

When we detect a in app route change (such as forgot password), we use `history.pushState` to update the URL and propagate a `popstate` event. 

If you have implemented your custom router, you are probably already be listening to this event and reload your router component when you detect it. The most basic way to implement router in React could looks like: 

https://github.com/supertokens/supertokens-auth-react/blob/0.0/test/react-test-app/src/AppWithoutRouter.js#L25

This is not going to work out of the box if you use SuperTokens without router in a new app (unless you add the event listener as described above).

In documentation we could:
 - recommend using `react-router-dom` for fresh apps.
 - If they use custom router, let them know that they should listen to the `popstate` event to reload their routing component (if they are not doing it already).

**Comment by NkxxkN** [comment]
Let's fully reload the page instead so that it works as is.

**Comment by rishabhpoddar** [comment]
@rishabhpoddar what about the `rid` point mentioned in this issue. Is that solved too?

**Comment by NkxxkN** [comment]
Both are solved.
