### ISSUE TITLE
Implement a recipeModule manager

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#4]
Should be responsible for:
- Provide [routing functionality](https://github.com/supertokens/supertokens-auth-react/issues/4#issuecomment-709993403). The algorithm is [here](https://github.com/supertokens/supertokens-auth-react/issues/4#issuecomment-712193998).

- Has a way for any module to get the `appInfo` if needed.

- Has an init function that takes:
   - The [appInfo](https://github.com/supertokens/supertokens-auth-react/issues/4#issuecomment-709977157)
   - `recipeList`: RecipeModule[]

- Provides an abstract `recipeModule` class that modules must `extend`:
   - Provides methods to asks a module if they can handle the current route (excluding `websiteBasePath`).
   - Get and manage the module's `rId`. The `rId` will be an argument to the constructor.
   - Exposes a function that modules must implement to handle the current route.

- Recipe modules must be build such that parent recipe's `rId` can be propagated to them. [This is how](https://github.com/supertokens/supertokens-auth-react/issues/4#issuecomment-709991055)

**Comment by rishabhpoddar** [comment]
@NkxxkN please review the above

**Comment by rishabhpoddar** [comment]
## AppInfo in the init function:
```
{
   appName: string,
   websiteDomain: string,
   apiDomain: string
   logoFullURL?: string, // Default is ""
   apiBasePath?: string, // Default is `/auth`
   websiteBasePath?: string // Default is `/auth`
}
```

**Comment by rishabhpoddar** [comment]
## If a recipe is being built on top of another one, how can its `rId` be propogated down?

### Base recipe
```jsx
class EmailPassword extends RecipeModule {
	
	static instance: undefined | EmailPassoword

	constructor(options: {}, recipeId) {
		super(recipeId)
	}

	static getInstanceIfDefined() => {
		if (instance === undefined) {
			throw error("...");
		}
		return instance;
	}

	static init(options: {..}): ModuleInterface {
		instance = new EmailPassowrd(options, "emailpassword")
	}
	
}

// feature
class SignInUp extends React.Component {

	getEmailPassowordInstance = () => {
		let instance;
		if (this.props.__internal !== undefined && this.props.__internal.instance !== undefined) {
			instance = this.props.__internal.instance;
		} else {
			instance = EmailPassword.getInstanceIfDefined();
		}
		return instance;
	}
	
	defaultCallSignUp = () => {
		let rId = getEmailPassowordInstance().getRecipeId();
	}	

}
```

### New recipe
```jsx

class EmailPasswordModified extends RecipeModule {
	
	static instance: undefined | EmailPasswordModified

	emailPasswordInstance: EmailPassowrd;

	constructor(options: {}, recipeId) {
		super(recipeId)
		this.emailPasswordInstance = new EmailPassword(<options specific to this one>, 
				this.getRecipeId())
	}

	static getInstanceIfDefined() => {
		if (instance === undefined) {
			throw error("...");
		}
		return instance;
	}

	static init(options: {..}): ModuleInterface {
		// create a singleton instance of EmailPassword
		instance = new EmailPasswordModified(options, "emailpasswordmodified")
	}

}

// feature
class SignInUpModified extends React.Component {

	getEmailPassowordModifiedInstance = () => {
		let instance;
		if (this.props.__internal !== undefined && this.props.__internal.instance !== undefined) {
			instance = this.props.__internal.instance;
		} else {
			instance = EmailPasswordModified.getInstanceIfDefined();
		}
		return instance;
	}

	render() {
		return (
			<SignInUp
			{...this.props}
			__internal: {
				instance: this.getEmailPassowordModifiedInstance().emailPasswordInstance
				...this.props.__internal
			}
			{...this.props.children}
			/>
		);
	}
}
```

**Comment by rishabhpoddar** [comment]
## All routing functions / components
### With React route
```jsx
import {SuperTokensRoute} from "supertokens-auth-react"

<Router history={history}>
   <NavBar />
      <Switch>
         <SuperTokensRoute />
      </Switch>
   <Footer />
</Router>
```

### Manual routing
```jsx
import SuperTokens from "supertokens-auth-react"

if (SuperTokens.canHandleRoute()) {
   return SuperTokens.getRoutingComponent()
}
```

- Internally `SuperTokensRoute` uses `SuperTokens.getRoutingComponent()`

**Comment by NkxxkN** [comment]
> Provide routing functionality which:

  > If 0 modules say yes, then redirects the user to / 

We should not actually take care of any redirection, that would break customer's app. We should simply inform the router that we do not are not responsible for this route. The router will take care of managing the rest of the routing accordingly.

New proposition to optimise a little bit and make sure we do not loop over routes if we know already that the `rid` doesn't match:

**Case `rid` is present:**
- Ask all modules if they can handle the current route.
     -  `rid` doesn't match, then skip.
- Return matching module (only one), or return nothing (router will take care of any redirection itself).

**Case no `rid` is present:**:
- Return the first component that matches the route.

**Comment by NkxxkN** [comment]
Maybe we can rename `getEmailPassowordInstance` and `getEmailPassowordModifiedInstance` to be `getRecipe`? 
That makes it more consistent across all the features?

**Comment by rishabhpoddar** [comment]
> We should not actually take care of any redirection, that would break customer's app. We should simply inform the router that we do not are not responsible for this route. The router will take care of managing the rest of the routing accordingly.

Make sense! Good catch.

> New proposition to optimise a little bit

Makes sense. I have updated my original comment to point to your routing algo.

> Maybe we can rename getEmailPassowordInstance and getEmailPassowordModifiedInstance to be getRecipe?
That makes it more consistent across all the features?

How about `getRecipeInstanceOrThrow` for both? So it will become `EmailPassword.getRecipeInstanceOrThrowError()` and `EmailPasswordModified.getRecipeInstanceOrThrowError()`.
