### ISSUE TITLE
global is not defined error

### ISSUE THREAD

**Issue by kali-kb** [supertokens/supertokens-auth-react#409]
I followed the guide every bit of the instruction there but somehow I get this "global is not defined" error and I couldn't figure out what the problem is can somebody help? I'm using react v17.0.2 if it has anything to do with it thanks in advance

**Comment by anmilleriii** [comment]
Duplicate, see https://github.com/supertokens/supertokens-auth-react/issues/410#issuecomment-1089572391

**Comment by rishabhpoddar** [comment]
Closing this since this is a duplicate issue as mentioned by @anmilleriii
