### ISSUE TITLE
Broken Stylesheet - After building React Callback page css is broken

### ISSUE THREAD

**Issue by sgnilreutr** [supertokens/supertokens-auth-react#421]
![Screenshot 2022-04-11 at 20 06 19](https://user-images.githubusercontent.com/41041655/162890602-39abd5d3-e1bb-4eb8-8ac5-eb14c1969a61.png)

The above message was received after building and serving it on localhost and on a server.
`"supertokens-auth-react": "^0.20.4"`
`"@emotion/react": "^11.9.0"`
`"react": "^17.0.2"`

Codesplitting was removed from the project at the time of testing.

**Comment by sgnilreutr** [comment]
This is happening whenever the callback page of the Google Social login is triggered.

My setup is React and NodeJS. These are my setups:

- Backend SuperToken: https://github.com/Elysium-Labs-EU/juno-backend-service/blob/super-tokens/src/google/superToken.ts
- Backend App: https://github.com/Elysium-Labs-EU/juno-backend-service/blob/super-tokens/src/routes/app.ts
- Frontend Routes: https://github.com/Elysium-Labs-EU/juno-core/blob/9434aa727c780202cdfb9ee1f74b09cb27342352/src/App.tsx
- Frontend SuperToken: https://github.com/Elysium-Labs-EU/juno-core/blob/9434aa727c780202cdfb9ee1f74b09cb27342352/src/index.tsx

The setup works on my local.

**Comment by rishabhpoddar** [comment]
So from the other logs in the console, it seems that there is some issue with how the herokuapp's CSS is being loaded. It says "The stylesheet https://...chunk.css was not loaded because its MIME type, "text/html", is not "text/css".

This indicates some error in how the herokuapp is serving the file. Maybe check the config there? This doesn't seem to be supertokens related.

**Comment by sgnilreutr** [comment]
![Screenshot 2022-04-12 at 08 32 01](https://user-images.githubusercontent.com/41041655/162895458-be5b097a-ea31-4c42-b08b-ea6d6471510d.png)

**Comment by rishabhpoddar** [comment]
The Content-Type in the response header says text/html, but it should be text/css. So please check your server code that is serving this file. Make sure that for CSS files, it sends the Content-Type has text/css.

**Comment by sgnilreutr** [comment]
> The Content-Type in the response header says text/html, but it should be text/css. So please check your server code that is serving this file. Make sure that for CSS files, it sends the Content-Type has text/css.

The issue is not server related. **Local** has the same issue - meaning there is something going wrong during the build, since development works fine.

**Comment by rishabhpoddar** [comment]
There are no dependencies on any `.css` files that we have. All of our CSS is specified in JS files loaded via emotion.

**Comment by sgnilreutr** [comment]
@rishabhpoddar I will be debugging this in the oncoming days. Once resolved I will revert it back to you for the knowledge.

**Comment by sgnilreutr** [comment]
@rishabhpoddar I was unable to pinpoint the issue and therefor unable to fix it. I have decided to not move forward with Supertokens for now.
I would like to emphasize that I am unable to determine if the issue is solely caused by the SuperTokens implementation.
