### ISSUE TITLE
If a user has a tall footer, it will not make the login box smaller

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#43]
It seems that the login box's height and width takes precedence over other item's height and width.

If you run the [demo app](https://github.com/supertokens/supertokens-demo-react) and go from sign in to reset password UI, you will see that the footer size increases. That is because the sign in form is squashing the footer it seems.

I am not sure about this issue since it could be something wrong with my CSS

**Comment by rishabhpoddar** [comment]
if this is done, please close it too

**Comment by NkxxkN** [comment]
Fixed in the examples apps.
