### ISSUE TITLE
Large Bundle size

### ISSUE THREAD

**Issue by jeremylynch** [supertokens/supertokens-auth-react#442]
This is a great product and library. However my main criticism is the bundle size. 

Supertokens-auth-react: 590kb
libphonenumber: 350kb
react-phone-number-input: 212kb
supertokens-website: 133kb
chroma: 97kb
emotion 69kb

<img width="601" alt="image" src="https://user-images.githubusercontent.com/3665457/167297349-e48c6230-60a4-40a0-861e-56d5436de364.png">

Combined this is well over 1mb for the entire library. 

A few questions: 

1. Are we able to optionally drop libphonenumber/react-phone-number-input ? We are only using one country code and do not need this. 
2. Are we able to drop chroma? 
3. Is there a way we can delay loading the supertokens scripts to mitigate impact on performance?

**Comment by rishabhpoddar** [comment]
hey @jeremylynch the supertokens-auth-react SDK is split into different recipes which have their [own size limits](https://github.com/supertokens/supertokens-auth-react/blob/master/package.json#L101). Furthermore, the production, minified build for supertokens-website is [10kb](https://github.com/supertokens/supertokens-website/blob/master/package.json#L67). Is the above screenshot from a dev build?

At the moment, the initialisation of supertokens is done statically - this means that you must import from all the recipes you want to use upfront - this increases the bundle size.

We can explore an API change to make this more dynamic. But this will probably take a while.. For now, what you can do is to call `supertokens.init` with a different config based on which page is being loaded in your app. For example, on most pages of your app, you would need only the Session recipe (assuming you use the `SessionAuth` and not `EmailPasswordAuth` or `PasswordlessAuth`), then on those pages, you can initialise the `recipeList` with the session recipe and nothing more. For the login pages, you can use the EmailPassword and Passwordless recipe. 

This would of course require your app to not be an SPA, or at least not be an SPA for the login pages only. Anyhow, I do see this as a problem and we can work on solving this.

> Are we able to optionally drop libphonenumber/react-phone-number-input ? We are only using one country code and do not need this.
> Are we able to drop chroma?

Not easily. You can always fork the repo and make the change in the code yourself though.

> Is there a way we can delay loading the supertokens scripts to mitigate impact on performance?

I think my initial paragraph answers this question.

------------
If this is a deal breaking issue for you, you can always build your own UI and use just the supertokens-website SDK for session management - that should be ~10kb for production build

**Comment by porcellus** [comment]
Are you referring to the "stat size" that the bundle size analyzer gives? That is taken before minification and , please check the parsed/gzipped sizes.
Parsed size is the one that affects startup time and the Gzip size is representative of the amount of data that is transferred over the network.

**Comment by BrycensRanch** [comment]
> Contributor

https://bundlephobia.com/package/supertokens-auth-react@0.27.2

Seeing red on bundle analyzer gives me panic attacks. Thanks.

**Comment by rishabhpoddar** [comment]
hey @BrycensRanch we are in the process of getting rid of the emotion dependency which forms a huge part of the bundle size. Should be done within the next month.

**Comment by Romvnly-Gaming** [comment]
It's done. The work is done

**Comment by rishabhpoddar** [comment]
please use version >= 0.30.0
