### ISSUE TITLE
vite + supertokens-auth-react Build Error "pragma and pragmaFrag cannot be set when runtime is automatic"

### ISSUE THREAD

**Issue by davidstyrbjorn** [supertokens/supertokens-auth-react#457]
As the title says, I'm running a project which uses Vite + Supertokens and when i run `yarn build` i get the following error

`error during build:
SyntaxError: C:\programming\barker\barker-frontend\node_modules\supertokens-auth-react\lib\build\recipe\emailpassword\components\features\signInAndUp\index.js: pragma and pragmaFrag cannot be set when runtime is automatic.`

I will also post an image of my terminal log, I didn't find any easy way to paste the whole log

![image](https://user-images.githubusercontent.com/10048990/169498576-fff5d37f-0e7d-418d-a800-f4836c20bc8e.png)

I tried removing the `"use strict";` from the file, which didn't work.

I'm using 
`"supertokens-auth-react": "^0.20.4",`
`"vite": "^2.8.0"`
`"react": "^17.0.2",`

**Comment by rishabhpoddar** [comment]
We can possibly implement something as said in this SO question: https://stackoverflow.com/questions/66965774/emotion-css-prop-and-nextjs-new-jsx-runtime-error-pragma-and-pragmafrag-canno

**Comment by mwojcik-sdh** [comment]
Is there some workaround that can be used right now?

**Comment by rishabhpoddar** [comment]
@mwojcik-sdh you could fork the repo, make the change as mentioned in the SO answer and see if that works.

**Comment by talkingdonkeyz** [comment]
Apologies, I don't understand the SO post in this context. What do I need to add, and to which files? I really appreciate any help you can provide.

**Comment by rishabhpoddar** [comment]
@talkingdonkeyz i just tried the solution in the SO - doesn't seem to work. We are investigating another solution. Will keep this issue updated.

**Comment by rishabhpoddar** [comment]
This issue should have been solved in `v0.22.2`. Please feel free to reopen this issue in case the error persists.

**Comment by talkingdonkeyz** [comment]
I still get the same error but modifying the vite config with this seems to work.

`  plugins: [react({
    jsxRuntime: 'classic'
  })]`

I hope this helps anyone with the same issue.
