### ISSUE TITLE
Can't login using any iOS browser

### ISSUE THREAD

**Issue by olhapi** [supertokens/supertokens-auth-react#461]
Hello, @rishabhpoddar I think I've found an issue with supertokens-auth-react (0.21.3) + supertokens-node (9.2.1). The user tried to sign in using his iPhone and here are 2 scenarios that he encountered:

1) Using wrong login credentials he's getting a proper error message.
2) Using a proper login credentials he got redirected back to the sign in page. He is still getting an 'unauthorized' error after login, without any errors.

That happens only in iOS browsers (which is basically Safari underneath).

Video from the phone:
https://1drv.ms/v/s!AgCDDnfGXq0l3DarGwAjZH6o0Np_?e=XJvkQN

On backend there's nestjs server with supertokens module and createNewSession override (just in case).

Can you reproduce it?

**Comment by rishabhpoddar** [comment]
Hmm. I would need more info about this:
- What is the apiDomain and websiteDomain? On Safari, if they don't share the same domain (for example a.com vs b.com), then Safari won't send cookies by default. To solve this, we ask users to setup their api domain as a sub domain of their domain (for example a.com and api.a.com).
- If the api and website domains indeed share a common domain, then perhaps you could [enable debug logging](https://supertokens.com/docs/emailpassword/troubleshooting/how-to-troubleshoot) on the frontend and backend to see what's wrong? 
- Is this happening only on mobile device? O rveen desktop safari? If only mobile device, which OS version and model of the phone?

Thanks
