### ISSUE TITLE
Make running the tests easier

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#47]
It's not about the number of steps required, but about making sure that each step runs successfully and at the end, I am able to run the tests.

**Comment by NkxxkN** [comment]
This issue happened when using `CMD+C` after starting the tests.

I've added a trap mechanism to catch user shutdown and clean up.

Running the tests is just:

`npm run test`.

Feel free to reopen if the issue is still hapenning
