### ISSUE TITLE
Make it possible to get session info in the render function for react

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#49]
We should allow the user to do the following in the render function:
- Check if a user is logged in or not
- Get the userId
- Get JWT payload

It's not recommended to do those in the render function at the moment because they all read the browser storage, which is slow. Since render can be called many times, that means each time a slow operation like the above will cause a UI lag.

**Comment by NkxxkN** [comment]
We can leverage React context to wrap all logged in components into a `UserContext` higher order component (same way we did for Styles):


```js
import React from 'react'

import { UserProvider } from './UserContext'

function App() {
  return (
    <UserProvider>
      <LoggedInApp />
    </UserProvider>
  )
}
```


```js
import React from 'react'

const UserContext = React.createContext()

export const UserProvider = UserContext.Provider
export const UserConsumer = UserContext.Consumer

export default UserContext
```

```js
import React from 'react'
const UserContext = React.createContext()

export const UserConsumer = UserContext.Consumer

export function UserProvider () {
  if (doesSessionExist() == undefined) {
    // redirectToBasePath
  }

  const user = {
       id: getUserId(),
       sessionInfo: getJWTPayloadSecurely()
  }

  return (
    <UserContext.Provider value={user}>
      {children}
    </UserContext.Provider>
  )
}
```

Then in any components that is wrapper into the 

```js
import React, { Component } from 'react'
import UserContext from './UserContext'

class HomePage extends Component {
  static contextType = UserContext

  componentDidMount() {
    const user = this.context
  }

  render() {
    return <div>{user.id}</div>
  }
}
```


(^ Notice that this is a better way to access the context than what I did with styleContext (which is the legacy way), I'll make sure to update components using Style context)

The advantage is that you only read values from the browser storage once per SPA render.

Open question: What happens when user info is updated? How does the UserContext know about it?

**Comment by NkxxkN** [comment]
Created issue for the `redirect_to` feature https://github.com/supertokens/supertokens-auth-react/issues/77

Should we close that one and move it to `supertokens-website` ?

**Comment by rishabhpoddar** [comment]
I am not 100% sure that solving this issue is a SuperTokens-website only fix. It may require the use of react context. So I'd keep it here.

**Comment by NkxxkN** [comment]
Ok that's fair. 

Open question: How do we solve the issue of updating session infos if we use React context?

**Comment by rishabhpoddar** [comment]
Closing since this is partially done, and a new issue has been added to complete the rest of it: https://github.com/supertokens/supertokens-auth-react/issues/228
