### ISSUE TITLE
Implement the SignInAndUp Feature component

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#5]
- `import { SignInAndUp } from "supertokens-auth-react/recipe/emailpassword"`
- The default implementation should be in `${websiteBasePath}/`
- The default theme should be [SignInAndUpTheme](https://github.com/supertokens/supertokens-auth-react/issues/9)
- [Props for this component](https://github.com/supertokens/supertokens-auth-react/issues/5#issuecomment-709981135) (all optional, all must have a default implementation):
- Will pass the following down to the Theme component (along with whatever the user passes):
   - [signUpForm Object](https://github.com/supertokens/supertokens-auth-react/issues/5#issuecomment-709510099)
   - [signInForm Object](https://github.com/supertokens/supertokens-auth-react/issues/5#issuecomment-709510922)
- They must be responsible to render a `shadow-root` to prevent CSS clashes
- Should have its own config in the `init` function as explained [in this comment](https://github.com/supertokens/supertokens-auth-react/issues/5#issuecomment-709512438)
- On sign in / up, this feature will first apply the frontend validators. If they pass, it will call the API. This means that the user does not need to call the validators themselves in case they are building thier own theme

**Comment by rishabhpoddar** [comment]
```
signUp: {
   callAPI: (formFields: {id: string, value: string}[]) => Promise<{
   status: "FIELD_ERROR"
   fields: {
      id: string,
      error: string | undefiend
   }[]
} | {
   status: "GENERAL_ERROR", message: string} | {status: "OK"}>,
   onSuccess: () => void,
   formFields: {
      id: string,
      label: string,
      placeholder?: string
      validate?: (value) => Promise<string | undefiend>
   }[],
   styleFromInit: {...}
}
```

**Comment by rishabhpoddar** [comment]
```
signIn: {
   callAPI: (formFields: {id: string, value: string}[]) => Promise<{
   status: "FIELD_ERROR"
   fields: {
      id: "email" | "password",
      error: string | undefiend
   }[]
} | {
   status: "GENERAL_ERROR", message: string} | {status: "OK" | "SIGN_IN_WRONG_CREDENTIAL_ERROR"}>,
   onSuccess: () => void,
   formFields: {
      id: "email" | "password",
      label: string,
      placeholder?: string
      validate?: (value) => Promise<string | undefiend>
   }[],
   styleFromInit: {...}
}
```

**Comment by rishabhpoddar** [comment]
```
signInAndUpFeature: {
				overrideDefaultRoute: true,
				onSuccessRedirectURL: string,
				signUp: {
					formFields: {
						id: "email" | "password" | string,
						label: string,
						placeholder?: string,
						validateUserInput?: (value) => Promise<string | undefined>
					}[],
					style: {...}
				},

				signIn: {
					formFields: {
						id: "email" | "password",
						label: string,
						placeholder?: string,
						validate?: (value) => Promise<string | undefined>  // If not there, it will take validator from sign up
					}[],
					style: {...}
				}
			}
```

**Comment by rishabhpoddar** [comment]
## Props to Feature component
```
{
   onHandleSuccess(context: {action: "SESSION_ALREADY_EXISTS"} | {action: "SIGN_IN_COMPLETE" | "SIGN_UP_COMPLETE", user: {id: string, email: string}, responseJson): Promise<boolean>,
   onCallSignUpAPI(requestJson, headers): Promise<responseJson>,
   onCallSignInAPI(requestJson, headers): Promise<responseJson>, 
   doesSessionExist(): Promise<boolean>,
   onHandleForgotPasswordClicked(): Promise<boolean>,
}
```

**Comment by NkxxkN** [comment]
## Email validation
> Check that the email has the correct syntax
Sounds good. A regexp should do the trick.

## Password validation
> Check a minimum of 5 characters
I think 8 is a minimum.

> Is not some of the most common passwords (we can fetch a list of 100 top common ones?)

Interesting idea. Here is the most trusted list of common password: https://github.com/danielmiessler/SecLists/tree/master/Passwords/Common-Credentials

On the same note, I've seen websites showing an equivalent of what is done is https://random-ize.com/how-long-to-hack-pass/ while you add your password. I thought it was a really cool experience and it was a nice way to encourage having a strong password. 

> Anything else ? 
Do we enforce special characters, Uppercase and numbers by default? This is a very opinionated decision but it shows that SuperTokens takes authentication seriously.

## Login redirection
> how does the redirection work in an SPA? We do not want to fully reload the page right?

We will use: `history.pushState` to redirect without reloading in an SPA.

**Note**: Please feel free to remove this comment to keep the github issue clean. I wasn't sure how to collaborate properly here.

**Comment by rishabhpoddar** [comment]
@NkxxkN I think password can be 8 chars with a number by default. Have changed the comment above to reflect that

**Comment by rishabhpoddar** [comment]
@NkxxkN , the suggestions for password validation:
- Common password
- Time to break password UI
can be added in a separate theme perhaps.

**Comment by NkxxkN** [comment]
- Updated `validateUserInput` to `validate` to make it more consistent with the rest.

**Comment by NkxxkN** [comment]
> One more thing I noticed is that we do not pass the URL as a function param. perhaps we should and they could use that if they want, else they could use their own URL in case they have implemented their own custom API.

In default case we do `fetch(this.appInfo.apiDomain + "/signin", ...)` for instance, but that is done internally (in an HttpRequest module). No need to pass the path (`/signin`), we could pass the `apiDomain`, but if they are about to manage the call themselves, it might be because they are calling another API? Anyway, they have initialised SuperTokens with this same URL so they will likely have it in a `const` in the same file right?

**Comment by rishabhpoddar** [comment]
Actually, they could be using this function to just modify the request or do something else maybe and still want to call our default API. In that case, while they may know the `apiDomain`, they may not know it's `/signin`. Anyway, this is just a hypothetical and I'm not sure it even makes sense. So for now we don't need to pass the URL.

**Comment by NkxxkN** [comment]
> how does the redirection work in an SPA? We do not want to fully reload the page right?

I think we should actually reload the full page on login.

A lot of applications do load bunch of business related data on page load. If we do not reload the page, it will likely result in error states for most applications because there will be a session but the SaaS dashboards will not load properly.
We need to reload the page fully to make sure that these side effects do not happen. I think it's totally fine to do so as most applications do it.

**Comment by rishabhpoddar** [comment]
> A lot of applications do load bunch of business related data on page load. If we do not reload the page, it will likely result in error states for most applications because there will be a session but the SaaS dashboards will not load properly.
We need to reload the page fully to make sure that these side effects do not happen. I think it's totally fine to do so as most applications do it.

I'm OK with this, however, wouldn't people have this login in the `componentDidMount` function or using `useEffect`? Will those not get called if the page is shown (without a page reload)?
