### ISSUE TITLE
UserContext not working in Session.doesSessionExist

### ISSUE THREAD

**Issue by danieldunderfelt** [supertokens/supertokens-auth-react#514]
I'm trying to show the SignUpIn component when a user is logged in, but the userContext value I try to set to enable this is not available in the `Session.doesSessionExist` function.

I set the context like this:

```jsx
<ThirdPartyPasswordless.SignInAndUp
  userContext={{
    ignoreSession: true
  }}
/>
```

And the console.log here shows that input.userContext is an empty object:

```javascript
Session.init({
  override: {
    functions: (originalImplementation) => ({
      ...originalImplementation,
      doesSessionExist: (input) => {
        console.log(input)

        if (input.userContext?.ignoreSession) {
          return false
        }

        return originalImplementation.doesSessionExist(input)
      }
    })
  }
})
```

It should have `ignoreSession: true`.

**Comment by rishabhpoddar** [comment]
This issue should be fixed in v0.24.0.
