### ISSUE TITLE
Test, check and fix all example apps

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-auth-react#516]
Some of our examples seem to be broken. We should check that all of them are working properly and fix them if necessary. Some issues I noticed:

- with-jwt-localstorage: sign-out doesn't properly update (the override doesn't fire the SIGN_OUT event) + there are a few failing network calls.
- with-localstorage: completely broken, login not working, ends up in an infinite loop calling email verification
- with-thirdparty-2fa-passwordless: the disabled sign-up seems to be throwing a 500 instead of the intended error

**Comment by rishabhpoddar** [comment]
These example apps have been fixed.
