### ISSUE TITLE
context.isNewUser is undefined in ThirdPartyPasswordless getRedirectionURL

### ISSUE THREAD

**Issue by danieldunderfelt** [supertokens/supertokens-auth-react#519]
I'm trying to redirect new users to their profile after signing in, but the isNewUser prop is undefined in the getRedirectionURL function of ThirdPartyPasswordless.

Logging:

![Screenshot 2022-07-05 at 20 19 10](https://user-images.githubusercontent.com/3145668/177382579-520b0e49-9e74-4e9e-b833-66740c071714.png)

Result:

![image](https://user-images.githubusercontent.com/3145668/177382407-99ca84d5-2d7e-49cb-bca3-3847dfea8033.png)

**Comment by nkshah2** [comment]
@danieldunderfelt we have released a fix for one of the sub-dependencies. Can you uninstall supertokens-auth-react and reinstall it to see if the issue still persists?

```bash
npm un supertokens-auth-react
npm i supertokens-auth-react
```

PS: Ill leave the issue open for a few days just in case
