### ISSUE TITLE
mocha-multi should be devDependency?

### ISSUE THREAD

**Issue by JakeGinnivan** [supertokens/supertokens-auth-react#523]
I am using PNPM and when I install supertokens-auth-react I get a missing peer dependency of

```
├─┬ mocha-multi
  │ └── ✕ missing peer mocha@">=2.2.0 <7 || ^9"
```

I think mocha-multi could move to a dev dependency? Also emotion and possibly the other passwordless libraries should be peer dependencies to save apps having version conflicts?

**Comment by rishabhpoddar** [comment]
We have moved mocha-multi to devDependencies in version >= 0.24.1.
