### ISSUE TITLE
Electron app show 'Please provide a valid sessionScope' message

### ISSUE THREAD

**Issue by ShenTianyuKaiser** [supertokens/supertokens-auth-react#528]
I use supertokens-auth-react in my electron app.

```
SuperTokens.init({
  appInfo: {
    ...
    websiteDomain: 'https://localhost:8000',
    ...
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      ...
    }),
    Session.init(),
  ],
});
```

When I run it locally, it works well.
But when I build a release version, an error occurred and error message is 'Please provide a valid sessionScope'.
If I write this:
```
Session.init({
      sessionScope: 'localhost',
}),
```
There's no 'Please provide a valid sessionScope' and other error, but a empty window.

So what can I do now？

**Comment by ShenTianyuKaiser** [comment]
I saw the electron demo in example.
But I want to use supertokens-auth-react to initialize, not supertokens-node.

**Comment by rishabhpoddar** [comment]
@ShenTianyuKaiser localhost is not a valid value for `sessionScope`. The `sessionScope` is used for the `domain` config for each cookie that is set on the frontend. It is usually required when you want to share a session across sub domains (https://supertokens.com/docs/session/common-customizations/sessions/share-sessions-across-sub-domains).

So you shouldn't need to add it in an electron app.

Regarding the example app that we have, [here](https://github.com/supertokens/supertokens-auth-react/blob/master/examples/with-thirdpartypasswordless-electron/src/renderer.tsx#L59) is where we initialise supertokens-auth-react. The supertokens-node SDK is to be initialised on the backend server (if you are using node). We also support golang and python at the moment.

I'm closing this issue since it's not really a valid issue with the code. But feel free to reopen it if I missed something.

**Comment by ShenTianyuKaiser** [comment]
@rishabhpoddar 
Thank you very much.

So where should I write supertokens.init()?
In main process or rendering process?

Should I use supertokens-auth-react and write supertokens.init() in main process without 'sessionScope' param.
Is it right?

**Comment by rishabhpoddar** [comment]
You should put it in the rendering file, as shown in the example app.

And you don't need to add the `sessionScope` param

**Comment by ShenTianyuKaiser** [comment]
I run the example electron demo, it works well.
And I want to use my custom login UI so I modify the code:

```
SuperTokens.init({
    appInfo: {
        appName: "SuperTokens Demo App", // TODO: Your app name
        apiDomain: getApiDomain(), // TODO: Change to your app's API domain
        websiteDomain: getWebsiteDomain(), // TODO: Change to your app's website domain
        websiteBasePath: '/login',   //   I add this
    },
...
})
```
and this:
```
 <Router>
                    <div className="fill">
                        <Routes>
                            {/* This shows the login UI on "/auth" route */}
                            {/* {getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))} */}
                            <Route path="/login" element={<Login />}></Route> // I add my custom UI

                            <Route
                                path="/"
                                element={
                                    /* This protects the "/" route so that it shows 
                                        <Home /> only if the user is logged in.
                                        Else it redirects the user to "/auth" */
                                    <ThirdPartyPasswordless.ThirdPartyPasswordlessAuth
                                        onSessionExpired={() => {
                                            updateShowSessionExpiredPopup(true);
                                        }}>
                                        <Home />
                                        {showSessionExpiredPopup && <SessionExpiredPopup />}
                                    </ThirdPartyPasswordless.ThirdPartyPasswordlessAuth>
                                }
                            />
                        </Routes>
...
```
But there's another error message:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/93726543/179382372-5a2c4c0e-d85d-4882-812b-b28db7805155.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/93726543/179382377-ae0acd21-7be4-4d65-8853-faa6e4b0e772.png">

I cannot find the reason, please help me, thanks!

**Comment by rishabhpoddar** [comment]
Hey @ShenTianyuKaiser this seems to be an issue with the router package - especially since you have commented out the `getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))` part.
