### ISSUE TITLE
GitHub should be capitalized

### ISSUE THREAD

**Issue by morgante** [supertokens/supertokens-auth-react#539]
Right now, the third party auth provider shows `Continue with Github`, but `Github` should have a capital H (`GitHub`).

<img width="364" alt="image" src="https://user-images.githubusercontent.com/1627801/182013961-405a20d6-f9b3-42bb-8085-1c59736644a3.png">

**Comment by rishabhpoddar** [comment]
This has been fixed and released in >= v0.24.3
