### ISSUE TITLE
createPasswordlessCode function undefined in ThirdPartyPasswordless

### ISSUE THREAD

**Issue by BaumgartnerSimon** [supertokens/supertokens-auth-react#553]
Facing this error when trying to use `createPasswordlessCode` function from `ThirdPartyPasswordless`.

![image](https://user-images.githubusercontent.com/49682704/184130672-f0575a16-e06c-4745-8f0b-8d29670411d8.png)

**Comment by rishabhpoddar** [comment]
The error was in the supertokens-web-js SDK which is a dependency of this (supertokens-auth-react) SDK. This has been fixed in supertokens-web-js version >= 0.1.5.

Please remove package-lock.json and node_modules folder and reinstall.
