### ISSUE TITLE
Errormessage for incorrect login credentials is still visible after clicking the signup link

### ISSUE THREAD

**Issue by Luxaaa** [supertokens/supertokens-auth-react#561]
Hi,
If you provide wrong email/padding you're getting an error message. After clicking the singup link, the error message is still visible in the signup form.
I am using the ThirdPartyEmailPassword recipe and the version of the libary i'm using is 0.24.4 (should be the latest)
![signup](https://user-images.githubusercontent.com/35200689/184921163-e11489ae-f6f2-4a30-91f9-ee244a4786cf.png)

**Comment by rishabhpoddar** [comment]
Thanks for the issue. We are checking it out.

**Comment by rishabhpoddar** [comment]
This issue should be fixed in >= 0.24.6
