### ISSUE TITLE
`doRedirection` & `requireAuth`

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-auth-react#570]
The `doRedirection` and `requireAuth` props of `SessionAuth` interact in the following way:
`doRedirection`: controls if we redirect on a failing requirement (that can redirect, e.g.: session missing or email verification in the "REQUIRED" mode). Defaults to true.
`requireAuth`: controls if we require a session. Defaults to true.

Keep in mind that the render function of children may be called even if we are redirecting because of email verification. This is not the case for missing sessions.

| doRedirection 	| requireAuth 	| what happens -> 	| no session       	| session with not verified email 	|
|---------------	|-------------	|-----------------	|------------------	|---------------------------------	|
| true          	| true        	| ---             	| redirect to auth and render null 	| redirect to email verification  	|
| true          	| false       	| ---             	| render children  	| redirect to email verification  	|
| false         	| true        	| ---             	| render null      	| render children                 	|
| false         	| false       	| ---             	| render children  	| render children                 	|

Also connected to this is the `overrideGlobalClaimValidators` that you can use to control which validators are required in the current `SessionAuth`. In the table above, we assume that email verification is turned on with the `mode` set to `REQUIRED`.

**Comment by rishabhpoddar** [comment]
Closing this cause it's only for reference
