### ISSUE TITLE
app in broken state if supertokens user got deleted and email verification is enabled

### ISSUE THREAD

**Issue by n1ru4l** [supertokens/supertokens-auth-react#580]
I spotted some kind of bug on the front end that leaves the application in an unusable state as the HTTP call to `/api/auth/user/email/verify` raises the error `Error: Unknown User ID provided (and makes the app unusable)`. 

Full Stack on the backend of the original error:

```
Error: Unknown User ID provided
    at Recipe.<anonymous> (/app/node_modules/supertokens-node/lib/build/recipe/thirdpartyemailpassword/recipe.js:129:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/supertokens-node/lib/build/recipe/thirdpartyemailpassword/recipe.js:15:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I think this is related due to an account that was deleted but the `sAccessToken`, `sFrontToken`, `sIRTFrontend` and `sIdRefreshToken` cookies still are present on the frontend.

After deleting the cookies from the dev tools everything works fine!

It seems like there should be better handling of this edge case instead of instructing users to clear their cookies. 🤔 

This might be related to https://github.com/supertokens/supertokens-auth-react/issues/547 ?

**Comment by porcellus** [comment]
Thanks for filing this as an issue on GH; it's easier to track :)
I think it's unrelated to think linked issue. This should error should not get to the application and be handled inside the SDK.
We should trigger a session refresh on the frontend (so basically return a 401 as we do for an expired access token), because getting this error means that the user has an invalid session.

**Comment by rishabhpoddar** [comment]
This issue has been solved now. The email verification APIs will return a 401 in case of a deleted user which will redirect the user to the auth screen.
