### ISSUE TITLE
Do you have something like getSuperTokensRoutesForReactRouterDom for useRoutes (react-router-dom v6)?

### ISSUE THREAD

**Issue by komarovalexander** [supertokens/supertokens-auth-react#581]
Hi Team it is very cool that you have getSuperTokensRoutesForReactRouterDom for routes
```
<Routes>
	{getSuperTokensRoutesForReactRouterDom(reactRouterDom)}			
```
but do you have something simmilar for 
```
const element = useRoutes([
                 getSuperTokensRoutesForReactRouterDom(reactRouterDom),
		{
			path: '/',
			element: <Navigate to="/orgs" replace />,
		},
```
thanks!

**Comment by komarovalexander** [comment]
looks like this is a solution:
```
const routes = getSuperTokensRoutesForReactRouterDom(reactRouterDom);
	const element = useRoutes([
		...routes.map((r) => r.props),
		{
			path: '/', ...

```

**Comment by rishabhpoddar** [comment]
Hey @komarovalexander apologies for being unresponsive here. I had missed this.

But yea, I think you are right.

Since you have already proposed a working solution, I am closing this issue. Thanks!

**Comment by rishabhpoddar** [comment]
This approach also works in case someone is using `createBrowserRouter`

**Comment by devhindo** [comment]
an example as of today's latest versions of React, TypeScript, React Router and SuperTokens that shows the login page at `/auth`

```TypeScript
SuperTokens.init({});  /* copied from supertokens docs (details abstracted)*/

createRoot(document.getElementById('root')!).render(
  <StrictMode> 
    <SuperTokensWrapper>
      <BrowserRouter>
        <Navbar />
        <Routes>
        {getSuperTokensRoutesForReactRouterDom(reactRouterDom, [ThirdPartyPreBuiltUI, EmailPasswordPreBuiltUI])}
          <Route path="/" element={<Root />} />
          <Route path="contacts/:contactId" element={<Chat />} />
        </Routes>
      </BrowserRouter>
    </SuperTokensWrapper>
  </StrictMode>,
)

```

**Comment by akashjuneja** [comment]
SuperTokens.init({
	appInfo: {
		appName: "jobVerse",
		apiDomain: "http://localhost:8000",
		websiteDomain: "http://localhost:5173",
		websiteBasePath: "/auth",
		apiBasePath: "/auth",
	},
	recipeList: [EmailPassword.init(), Session.init()],
});

createRoot(document.getElementById('root')!).render(
  <StrictMode> 
    <SuperTokensWrapper>
      <BrowserRouter>
        <Navbar />
        <Routes>
        {getSuperTokensRoutesForReactRouterDom(reactRouterDom, [ EmailPasswordPreBuiltUI])}
          <Route path="/" element={<Root />} />
          <Route path="contacts/:contactId" element={<Chat />} />
        </Routes>
      </BrowserRouter>
    </SuperTokensWrapper>
  </StrictMode>,
)---- By doing this nothing is rendering on my ui , am i doing anything fancy ?
