### ISSUE TITLE
kebab-case for css properties error message on supertokens components

### ISSUE THREAD

**Issue by otlichnyy** [supertokens/supertokens-auth-react#593]
# Problem
`using kebab-case for css properties in objects is not supported. Did you mean WebkitTextFillColor?` error message. when supertokens components gets mounted in react app (and nextjs)
[localhost-1664372753064.log](https://github.com/supertokens/supertokens-auth-react/files/9665595/localhost-1664372753064.log)

# Steps to recreate
 - use `npx create-supertokens-app` and create any app, react or nextjs
 - or just follow any integration guide

# Check on System (problem found in) 
 - recipes `Email Password Login`
 - nextjs
 - reactjs

**Comment by rishabhpoddar** [comment]
Thanks! We will fix this very soon

**Comment by rishabhpoddar** [comment]
This should be fixed in version >= 0.26.4 of the supertokens-auth-react SDK.
