### ISSUE TITLE
can't sign in

### ISSUE THREAD

**Issue by raouln97** [supertokens/supertokens-auth-react#608]
Hi,

I am using my own UI to sign into supertokens.However, the signIn function provided by supertokens-auth-react/recipe/emailpassword uses a GET method rather than a POST method which isnt allowing us to sign in.

Any fixes?

**Comment by rishabhpoddar** [comment]
Which recipe are you talking about, and which function in that recipe are you using?

**Comment by raouln97** [comment]
we are using the emailpassword recipe and using the signIn function as seen below:

```
import { signIn } from 'supertokens-auth-react/recipe/emailpassword'

const response = await signIn({
      formFields: [
        {
          id: 'email',
          value: email,
        },
        {
          id: 'password',
          value: password,
        },
      ],
    })
```

**Comment by raouln97** [comment]
do you have an example for a custom UI implementation with nodejs backend?

**Comment by rishabhpoddar** [comment]
See our docs: https://supertokens.com/docs/emailpassword/custom-ui/email-password-login

It has very clear code snippets on how to use supertokens. Im closing this issue since it's not really a bug in the lib
