### ISSUE TITLE
Login page is not displaying when /login endpoint is accessed

### ISSUE THREAD

**Issue by Ashu999** [supertokens/supertokens-auth-react#611]
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import SuperTokens, { SuperTokensWrapper } from 'supertokens-auth-react';
import Passwordless from 'supertokens-auth-react/recipe/passwordless';
import Session from 'supertokens-auth-react/recipe/session';

SuperTokens.init({
  appInfo: {
    appName: 'my-app',
    apiDomain: 'http://localhost:80',
    websiteDomain: 'http://localhost:3000',
    apiBasePath: '/auth',
    websiteBasePath: '/login',
  },
  recipeList: [
    Passwordless.init({
      contactMethod: 'EMAIL_OR_PHONE',
    }),
    Session.init(),
  ],
});

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
console.log('sup: ', SuperTokens.canHandleRoute());
if (SuperTokens.canHandleRoute()) {
  // This renders the login UI on the /login route
  root.render(SuperTokens.getRoutingComponent());
} else
  root.render(
    <React.StrictMode>
      <SuperTokensWrapper>
        <App />
      </SuperTokensWrapper>
    </React.StrictMode>
  );
```
for` websiteBasePath: '/'` I can see the login screen on http://localhost:3000/
`conosle.log on SuperTokens.canHandleRoute() is returning true`

but if I set `websiteBasePath: '/login'`, and access http://localhost:3000/login, then getting: `Cannot GET /login`
`conosle.log on SuperTokens.canHandleRoute() is returning false`

React version: `"react": "^18.2.0"`

I'm following these docs: https://supertokens.com/docs/passwordless/pre-built-ui/setup/frontend
answer to "Do you use react-router-dom?" is No

**Comment by rishabhpoddar** [comment]
hey @Ashu999 

I'm not able to replicate this issue. I copy / pasted your code into a new react project and this is the output
<img width="1512" alt="Screenshot 2022-11-05 at 10 28 28" src="https://user-images.githubusercontent.com/2976287/200101981-4ee7755c-c520-4903-b85e-7e6624bee345.png">


As you can see, I am able to see the login UI, and the console output is `sup: true`

Can you maybe upload a project on github that can replicate this issue?

**Comment by Ashu999** [comment]
Hi @rishabhpoddar,
The issue was in my Webpack config. I found the solution here: https://stackoverflow.com/questions/43209666/react-router-v4-cannot-get-url
Got resolved by adding:
```
devServer: {
    historyApiFallback: true,
  }
```
Thanks for help
