### ISSUE TITLE
Initialising auth react should also initialise web-js

### ISSUE THREAD

**Issue by nkshah2** [supertokens/supertokens-auth-react#612]
Currently recipes inside of auth react independently initialise recipes in the web-js SDK. The problem with this approach is that for Custom UI the documentation refers to web-js for code snippets, and using WebJsRecipe.function will result in an error because web-js itself was never initialised.

A solution to this is to refactor supertokens-auth-react to initialise the web-js SDK during the `init` call (instead of the individual recipes approach). Recipes in auth react should not maintain an instance of individual web-js recipes and instead of WebJsRecipe.function format when making function calls

**Comment by rishabhpoddar** [comment]
Closing this issue in favour of https://github.com/supertokens/supertokens-auth-react/issues/616
