### ISSUE TITLE
Eliminate the need to do duplicate init of auth-react and web-js for non react apps that use pre built UI

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#616]
Auth react underneath uses web-js, for non react apps that use pre built UI, we ask the user to do web-js init on the main route and auth-react init on the supertokens UI route. 

This leads to bad docs and bad user experience. Ideally, we just want the user to do web-js init on the main route and use functions from auth-react without having to do init on it as well. This means even for react users, it will be web-js init and just importing stuff from auth-react.

For this to work, we will need to move auth-react specific configs like (see next comment)

Then auth-react will simply call web-js functions using the static imports. One side effect of this is that auth-react will no longer have recipe functions and things like firing events or redirection will not be overridable via recipe function override.

Advantages:
- No need for double init for non react users with pre built UI
- People using a combination of pre built and custom UI can use web-js functions as per the docs without issues.
- No need to expose recipe functions in auth-react -> lesser code to maintain.
- People using react, even with full custom UI, can take advantage of `<SessionWrapper>` and `<SessionAuth>`. this would require changes to the docs though to eliminate the use of UI switcher and to add a react specific tab everywhere.

**Comment by rishabhpoddar** [comment]
# Changes
- Recipe implementation doesn't need to be there anymore in auth-react
- auth-react init goes away
- The functions in auth-react that are exposed via the recipe index files don't need to be there anymore?
   - We should also get rid of `redirectToThirdPartyLogin`
- Configs that are specific to auth-react:
   - websiteDomain and websiteBasePath
   - languageTranslation
   - getRedirectionUrl
   - Recipe common stuff
      - getRedirectUrl
      - onHandleEvent
      - useShadowDom
      - palette & style
      - override -> component
   - EmailPassword
      - signInUpFeature
      - resetPasswordUsingTokenFeature
   - Email verifcation
      - As of this writing, "mode" config is not required in web-js, but it will be very soon.
      - disableDefaultUi
      - sendVerifyEmailScreen
      - verifyEmailLinkClickedScreen
   - Passwordless
      - contactMethod
      - validation functions
      - signInUpFeature
      - defaultCountry
      - guessInternationalPhoneNumberFromInputPhoneNumber
      - linkClickedScreenFeature
   - Session:
      - nothing
   - Thirdparty
      - signInUpFeature
      - OAuthcallbackscreen
- Docs:
   - TODO

**Comment by rishabhpoddar** [comment]
# Where should the auth-react specific config go?

We considered adding it to functions like getComponent() as a config, but then it causes issues like in the docs we would have to ask the user what type of routing they are doing everywhere.

Instead, we should add a prop to the `<SuperTokensWrapper>` component like `config` which takes whatever auth-react init takes today, except for recipe function override, and stuff that's in the web-js init.

**Comment by rishabhpoddar** [comment]
## How will bundling work in this case? 

TODO:
With this change, if someone is using html scripts, and they do web-js script init, then when auth-react does EmailPassword.signIn (for example), it will not be able to find the web-js init.

**Comment by rishabhpoddar** [comment]
# Approach 2:

Current auth-react init is mantained, but:
- supertokens.init and recipe init does not depend on react and it doesn't pull in react components.
   - component overrides is no longer part of this init, but can be passed as a prop to <SuperTokensWrapper>
- React components provided by us should be on a different import path (how does this affect script bundling? TODO)
- supertokens.init calls web-js.init as well
- no need for recipeImplmenetation in auth-react
- we continue to expose functions auth-react functions as expected.
- docs will have to change to have a separate tab for react in custom UI so that we can tell people to use auth-react SDK even for custom UI
- TODO: What should be the import path now of things like getComponent(), or canHandleRoute() or the react dom router function? Also, being able to embed components - what should be the import for those components?
-

**Comment by nkshah2** [comment]
- We can make another wrapper that allows users to pass overrides to instead of passing it to the root directly 
    - One advantage is with embedding components because you can use this special component just in that embed as opposed to the top level
- Allow overrides to be passed to the wrapper and to the component as props to enable top level overrides and embed level overrides
