### ISSUE TITLE
createCode function throwing error : custom otp implementation 

### ISSUE THREAD

**Issue by sreehari2003** [supertokens/supertokens-auth-react#639]
## supertokens  createCode function is not working when called via supertoken-auth-react package

 in documentaion shown [here](https://supertokens.com/docs/passwordless/custom-ui/login-otp) u guys are using st web js library but i tried using auth react package but not working properly 

![image](https://user-images.githubusercontent.com/66205494/210259942-7448f28c-869b-440c-b6a7-9489447e48d6.png)

![image](https://user-images.githubusercontent.com/66205494/210259907-07b40bc2-8d61-4bdf-b271-f129e422188f.png)

![image](https://user-images.githubusercontent.com/66205494/210259843-cb00d095-6113-4a1a-a7cd-5f2c2bdcefba.png)

**Comment by porcellus** [comment]
Do you have a repo/code I could take a look at? I tried to reproduce this, but it worked as expected.

**Comment by sreehari2003** [comment]
> Do you have a repo/code I could take a look at? I tried to reproduce this, but it worked as expected.

you can see the code [here](https://github.com/sreehari2003/platform/blob/feat/customlogin/apps/web/pages/auth/%5B%5B...paths%5D%5D.tsx)

you used supertoken-auth-react package right ?  

only issue i am facing right now is sending otp ! that consumeCode fumction in notworking as expected @porcellus

**Comment by porcellus** [comment]
This may have been fixed by: https://github.com/supertokens/supertokens-web-js/pull/58
Please try updating the web-js dependency (auth-react & node is also a few versions behind) and let me know if it worked.

**Comment by sreehari2003** [comment]
> This may have been fixed by: [supertokens/supertokens-web-js#58](https://github.com/supertokens/supertokens-web-js/pull/58) Please try updating the web-js dependency (auth-react & node is also a few versions behind) and let me know if it worked.

So you want me to use both supertoken-web-js and  supertoken-auth-react in a single app?

**Comment by porcellus** [comment]
No, you just have to update your dependencies.

**Comment by sreehari2003** [comment]
> No, you just have to update your dependencies.

hey thank you for the help ,issue has been resolved !
 i am closing the issue
