### ISSUE TITLE
Have to login twice with Google auth provider

### ISSUE THREAD

**Issue by CyberneticTurtle** [supertokens/supertokens-auth-react#656]
I just upgraded our frontend to use v0.31.1 to match the backend (supertokens-python v0.12.1) but now users have to login twice with the Google auth provider. Or more precisely, if they aren't already logged into a Google account, they have to login twice into the website.

It seems like if you are directed to a "Google Login" page, the redirect after a successful login does not set the appropriate cookies in the frontend (confirmed via dev tools), so we get a "Something went wrong. Please try again." error. But if the user is already signed into a Google account (i.e. in this case, press the button a second time), then the appropriate cookies are set and the user is authenticated.

This can easily be replicated (at least for me) using a private/incognito browser window.

I haven't tried with other auth providers yet.

EDIT: Actually tested it with 0.30.2 (+ supertokens-python v0.11.13) as well and it has the same bug. Have to click the login with Google link twice if you are not already signed into Google.

**Comment by rishabhpoddar** [comment]
Hi @CyberneticTurtle 
- Can you show me the API response and request headers for the signinup API call (for the first and second login attempt)? A screenshot from chrome will do.
- Can you show me the cookie store contents before first login attempt, after first login attempt, and after second login (successful) attempt? A screenshot will do.

**Comment by rishabhpoddar** [comment]
Usually this shouldn't matter. But what might cause an issue is if there is time skew on your system.
