### ISSUE TITLE
Show user their last used OAuth provider for sign in

### ISSUE THREAD

**Issue by makerboiAdi** [supertokens/supertokens-auth-react#658]
When a user is logging in, show them the last used social provider and ideally their last used email ID. Similar to this twitter thread,

https://twitter.com/swyx/status/1626331120655810560 (also has implementation details)

**Comment by rishabhpoddar** [comment]
@makerboiAdi @mufassirkazi will need design for this first.

**Comment by mufassirkazi** [comment]
Imo, it doesn't make sense to show for last used email. Although:

- We can autofill the last used email with the password field in focus. If they click on the email field we can completely remove the registered entry
- We can show a small line saying last used: [youremail@gmail.com](mailto:youremail@gmail.com) and clicking on that prefills
- We do nothing and leave to the browser to autofill depending on the most used emails that the user uses in that browser

For last used provider, these are the design options: 

<img width="419" alt="Screenshot 2023-02-23 at 2 02 49 PM" src="https://user-images.githubusercontent.com/46087290/220857023-16cdf53e-2cb0-4ec6-a9f4-891f931e1789.png">

<img width="444" alt="Screenshot 2023-02-23 at 2 03 12 PM" src="https://user-images.githubusercontent.com/46087290/220857101-30044b2b-8f78-45e3-80c9-3dc0e7b75ecf.png">

<img width="723" alt="Screenshot 2023-02-23 at 2 03 03 PM" src="https://user-images.githubusercontent.com/46087290/220857067-131e0230-29c2-4bfc-b0ca-5a35ad70df33.png">

<img width="742" alt="Screenshot 2023-02-23 at 2 03 28 PM" src="https://user-images.githubusercontent.com/46087290/220857137-4f6c2092-85f6-40df-9814-465a22fb8073.png">

**Comment by mufassirkazi** [comment]
Final selection: 

<img width="710" alt="Screenshot 2023-03-01 at 4 14 51 PM" src="https://user-images.githubusercontent.com/46087290/222117245-cbbd5917-a974-4a37-8adf-223ed5c07a9c.png">
