### ISSUE TITLE
Vue error

### ISSUE THREAD

**Issue by insky** [supertokens/supertokens-auth-react#661]
After updating from 0.29.0 app crashes with error
<img width="928" alt="Screenshot 2023-03-03 at 13 21 36" src="https://user-images.githubusercontent.com/1969771/222708086-ed982b70-68b8-4caa-a92c-dc506aa8ea36.png">

**Comment by rishabhpoddar** [comment]
Hey @insky did you provide a custom style to supertokens.init on the frontend? If so, how? There was a change in how styles is provided in the latest version of the SDK (see the SDK changelog please)

**Comment by insky** [comment]
Yes, that's the point. Config has style property as Object, now it must be string

**Comment by rishabhpoddar** [comment]
Alright. Closing this issue since it's not really a bug in our SDKs.
