### ISSUE TITLE
NPM version warning

### ISSUE THREAD

**Issue by LeanderGangso** [supertokens/supertokens-auth-react#666]
Got this error when installing auth-react or web-js.

![image.png](https://user-images.githubusercontent.com/60340480/226824386-c62fc735-40e6-4db7-b3b1-05d7684f4ad9.png)

Reproduce:
`npm create vite@latest`
`npm install supertokens-...`

Edit:
Sidenote tested on npm -v 8.19.2 and that ofc worked just fine.

**Comment by rishabhpoddar** [comment]
This warning should be fixed in version >= 0.31.3
