### ISSUE TITLE
Form validators on blur

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#70]
Currently we run the validators for all fields when clicking on submit button.

Improvement suggestion: Run validators when an input looses focus (on blur) to have immediate feedbacks.

**Comment by NkxxkN** [comment]
@mufassirkazi Should we move forward with that one?

**Comment by mufassirkazi** [comment]
Yes please

**Comment by mufassirkazi** [comment]
As suggested by you Kevin, we should have the Sign in / up button disabled if there are existing errors in the form fields
