### ISSUE TITLE
KeyError: 'access_token' in Flask Python backend (during sign in on NextJS frontend)

### ISSUE THREAD

**Issue by alxiang** [supertokens/supertokens-auth-react#707]
Once in a while my backend (Flask) has an error during the signinandup flow on the frontend, when the user tries to sign in with Google. On the frontend, there's an error like "there was an error, please retry" and on the next attempt, the user can sign in fine. This also doesn't always happen (i.e. most of the time, the user is able to sign in with google with no errors).

We're using supertokens-python on the backend (version 0.13.1) and supertokens-auth-react on the frontend (version 0.32.3). Our website is at [www.wayfind.live](https://www.wayfind.live). We're using the default auth page—here is our frontendConfig:

`export const frontendConfig = () => {
  return {
    appInfo,
    recipeList: [
      ThirdPartyEmailPasswordReact.init({
        getRedirectionURL: async (context) => {
          if (context.action === "SUCCESS") {
              if (context.redirectToPath !== undefined) {
                  // we are navigating back to where the user was before they authenticated
                  return context.redirectToPath;
              }
              return "/";
          }
          return undefined;
        },
        useShadowDom: false,
        style: ...,
        signInAndUpFeature: {
          defaultToSignUp: true,
          disableDefaultUI: false,
          providers: [
            ThirdPartyEmailPasswordReact.Google.init(),
            ThirdPartyEmailPasswordReact.Facebook.init(),
          ],
          signUpForm: {
            termsOfServiceLink: "https://www.wayfind.live/terms",
            privacyPolicyLink: "https://www.wayfind.live/privacy"
          }
        },
      }),
      SessionReact.init({
        tokenTransferMethod: "header",
      }),
    ],
    windowHandler: (oI: any) => {
      return {
        ...oI,
        location: {
          ...oI.location,
          setHref: (href: string) => {
            Router.push(href)
          },
        },
      }
    },
  }
}`

Here's the traceback in the backend:
`
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in full_dispatch_request rv = self.preprocess_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2312, in preprocess_request rv = self.ensure_sync(before_func)() File "/usr/local/lib/python3.9/site-packages/supertokens_python/framework/flask/flaskmiddleware.py", line 54, in  result: Union[BaseResponse, None] = sync(st.middleware(request, response)) File "/usr/local/lib/python3.9/site-packages/supertokens_python/async_to_sync_wrapper.py", line 33, in sync return loop.run_until_complete(co) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/supertokens_python/supertokens.py", line 519, in middleware api_resp = await matched_recipe.handle_api_request( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdpartyemailpassword/recipe.py", line 231, in handle_api_request return await self.third_party_recipe.handle_api_request( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdparty/recipe.py", line 133, in handle_api_request return await handle_sign_in_up_api(self.api_implementation, api_options) File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdparty/api/signinup.py", line 79, in handle_sign_in_up_api result = await api_implementation.sign_in_up_post( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdpartyemailpassword/api/thirdparty_api_implementation.py", line 63, in sign_in_up_post result = await api_implementation.thirdparty_sign_in_up_post( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdpartyemailpassword/api/implementation.py", line 144, in thirdparty_sign_in_up_post result = await self.tp_sign_in_up_post( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdparty/api/implementation.py", line 151, in sign_in_up_post user_info: UserInfo = await provider.get_profile_info( File "/usr/local/lib/python3.9/site-packages/supertokens_python/recipe/thirdparty/providers/google.py", line 58, in get_profile_info access_token: str = auth_code_response["access_token"] KeyError: 'access_token'
`

Here's what the frontend looks like after the error:
![](https://cdn.discordapp.com/attachments/1113510798736752692/1113544435238719570/Screenshot_2023-05-31_at_3.07.49_PM.png)

**Comment by alxiang** [comment]
This is our _app.tsx:

```
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Navbar from "@/pages/components/Navbar";
import { Analytics } from "@vercel/analytics/react";
import { useRouter } from "next/router";

import SuperTokensReact, { SuperTokensWrapper } from "supertokens-auth-react";
import { frontendConfig } from "../config/frontendConfig";

import posthog from "posthog-js";
import { PostHogProvider } from "posthog-js/react";
import { useEffect } from "react";

if (typeof window !== "undefined") {
  // we only want to call this init function on the frontend, so we check typeof window !== 'undefined'
  SuperTokensReact.init(frontendConfig());

  posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY || "", {
    api_host: "https://app.posthog.com",
    // Enable debug mode in development
    loaded: (posthog) => {
      if (process.env.NODE_ENV === "development") posthog.debug();
    },
  });
}
export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();

  useEffect(() => {
    // Track page views
    const handleRouteChange = () => posthog?.capture("$pageview");
    router.events.on("routeChangeComplete", handleRouteChange);

    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, []);

  return (
    <>
      <Navbar style={router.pathname == "/" ? { border: "none" } : {}} />
      <SuperTokensWrapper>
        <PostHogProvider client={posthog}>
          <Component key={router.asPath} {...pageProps} />
        </PostHogProvider>
      </SuperTokensWrapper>
      <Analytics />
    </>
  );
}
```

Here's our frontendConfig.ts:

```
import ThirdPartyEmailPasswordReact from 'supertokens-auth-react/recipe/thirdpartyemailpassword'
import SessionReact from 'supertokens-auth-react/recipe/session'
import { appInfo } from './appInfo'
import Router from 'next/router'

export const frontendConfig = () => {
  return {
    appInfo,
    recipeList: [
      ThirdPartyEmailPasswordReact.init({
        getRedirectionURL: async (context) => {
          if (context.action === "SUCCESS") {
              if (context.redirectToPath !== undefined) {
                  // we are navigating back to where the user was before they authenticated
                  return context.redirectToPath;
              }
              return "/";
          }
          return undefined;
        },
        useShadowDom: false,
        style: `
            [data-supertokens~=container] {
                // --palette-background: 51, 51, 51;
                // --palette-inputBackground: 41, 41, 41;
                // --palette-inputBorder: 41, 41, 41;
                // --palette-textTitle: 255, 255, 255;
                // --palette-textLabel: 255, 255, 255;
                // --palette-textPrimary: 255, 255, 255;
                // --palette-error: 173, 46, 46;
                // --palette-textInput: 169, 169, 169;
                // --palette-textLink: 169, 169, 169;
                font-family: Montserrat;
                [data-supertokens=button] {
                  background-color: #65B790;
                  border: 0px;
                  width: 30%;
                  margin: 0 auto;
                }
                [data-supertokens=superTokensBranding] {
                  display: none;
                }
            }
        `,
        signInAndUpFeature: {
          defaultToSignUp: true,
          disableDefaultUI: false,
          providers: [
            ThirdPartyEmailPasswordReact.Google.init(),
            ThirdPartyEmailPasswordReact.Facebook.init(),
            // ThirdPartyEmailPasswordReact.Github.init(),
            // ThirdPartyEmailPasswordReact.Apple.init(),
          ],
          signUpForm: {
            termsOfServiceLink: "https://www.wayfind.live/terms",
            privacyPolicyLink: "https://www.wayfind.live/privacy"
          }
        },
      }),
      SessionReact.init({
        tokenTransferMethod: "header",
      }),
    ],
    windowHandler: (oI: any) => {
      return {
        ...oI,
        location: {
          ...oI.location,
          setHref: (href: string) => {
            Router.push(href)
          },
        },
      }
    },
  }
}
```

Here's our appInfo.ts:
```
export const appInfo = {
  // learn more about this on https://supertokens.com/docs/thirdpartyemailpassword/appinfo
  appName: "Wayfind",
  apiDomain: process.env.NEXT_PUBLIC_REACT_APP_BACKEND_URL || "http://localhost:8000",
  websiteDomain: process.env.NEXT_PUBLIC_WEBSITE_DOMAIN || "http://localhost:3000",
  apiBasePath: "/auth",
  websiteBasePath: "/auth"
}
```

**Comment by porcellus** [comment]
Can you add the component that renders the sign-in UI as well? In our examples it's `pages/auth/[[...path]].tsx`

**Comment by alxiang** [comment]
Oh yeah of course, we have it add that same path:

```
import React, { useEffect } from 'react'
import dynamic from 'next/dynamic'
import { ThirdPartyEmailPasswordPreBuiltUI } from "supertokens-auth-react/recipe/thirdpartyemailpassword/prebuiltui";
import { redirectToAuth } from 'supertokens-auth-react'
import { canHandleRoute, getRoutingComponent } from 'supertokens-auth-react/ui'

const SuperTokensComponentNoSSR = dynamic<{}>(
  new Promise((res) => res(() => getRoutingComponent([ThirdPartyEmailPasswordPreBuiltUI]))),
  { ssr: false }
)

export default function Auth() {

  // if the user visits a page that is not handled by us (like /auth/random), then we redirect them back to the auth page.
  useEffect(() => {
    if (canHandleRoute([ThirdPartyEmailPasswordPreBuiltUI]) === false) { 
      redirectToAuth()
    }
  }, [])

  return (
      <SuperTokensComponentNoSSR />
  )
}
```

**Comment by porcellus** [comment]
I've found the issue: in `_app.tsx` you added `key={router.asPath}` to `Component`. Since `router.asPath` changes between hydration and the first browser render, this means that all components (including our sign-in widget) get re-mounted. This may not have been what you tried to achieve. Since we can't really detect this from inside our components. You could try:

**Comment by alxiang** [comment]
Thanks for finding this! I was able to check that `key={router.asPath}` was the problem as well. For our case, what seems to be working is only using the `router.asPath` key if router.pathname matches certain paths (since we still want to refresh on certain `router.asPath`).
