### ISSUE TITLE
Add a "back to login" link to reset password

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#71]
Examples:

![image](https://user-images.githubusercontent.com/5072452/100115551-f23a7980-2e72-11eb-8228-b9c2b571be58.png)

![image](https://user-images.githubusercontent.com/5072452/100115575-f8c8f100-2e72-11eb-8992-ad4d30e3453c.png)

![image](https://user-images.githubusercontent.com/5072452/100115626-07170d00-2e73-11eb-9a5a-40645b172903.png)

**Comment by rishabhpoddar** [comment]
I believe that Mufassir had made some UI for this - a simple back arrow on the top left. But I'm open to anything. Please consult design related issues with him.

**Comment by NkxxkN** [comment]
@mufassirkazi any opinion on that one?

**Comment by mufassirkazi** [comment]
A simple back arrow button should suffice. Will update v2 designs to include this update

**Comment by NkxxkN** [comment]
Closing as it will be on new designs
