### ISSUE TITLE
Example Issue on "with-one-login-per-subdomain"

### ISSUE THREAD

**Issue by jinsato0422** [supertokens/supertokens-auth-react#718]
I'm trying to follow the example app code regarding the "with-one-login-per-subdomain" folder.
I followed the read.me file and did the last command "npm i && npm start" but I ended up with a error with: 
`> supertokens-auth-react@0.33.1 front
> (cd ./examples/for-tests/ && BROWSER=none PORT=3031 npm run start)        

> supertokens-auth-react@0.33.1 server> cd test/server/ && START=true INSTALL_PATH=../../../supertokens-root NODE_PORT=8082 node .

'BROWSER' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "front" exited with 1.`

Please take a look

**Comment by rishabhpoddar** [comment]
hey. You are `cd`ing into the `for-tests` app, which is not related to `with-one-login-per-subdomain` in any way.

**Comment by jinsato0422** [comment]
Hmm I can't seem to register my gmail

**Comment by rishabhpoddar** [comment]
Hey. We are going to redo the app for multi tenancy in a few weeks anyway. So this example app is no more applicable. Im closing this issue for now.
