### ISSUE TITLE
v0.2.0 Changes

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#74]
### Bug fixes
- [x] autocomplete email and password
- [x] Give space to password managers: remove success tick and move error tick to validation errror.

### New features
 - Form validation on blur
 - VerifyEmailExists `SignInAndUp` props

**Form validation on blur**
- [x] New FDI Spec 1.4.0 https://github.com/supertokens/frontend-driver-interface/pull/4
- [x] Implement new FDI feature
- [x] Update `auth-react` with `supertokens-node` version
- [x] Verify if email exists on blur
- [x] Use your own verifyEmailExist props
- [x] Add verifyEmailExists props to auth-react doc
 - [x] `DefaultToSignUp` config and default widget to sign up form.

**Comment by rishabhpoddar** [comment]
Why don't we have the design changes in the version too?

**Comment by NkxxkN** [comment]
Depending on the amount of work for redesign we will do everything in 0.2.
