### ISSUE TITLE
Create Remix example for TPEP recipe

### ISSUE THREAD

**Issue by mawentowski** [supertokens/supertokens-auth-react#795]
- Create an example Remix app for the thirdpartyemailpassword recipe and add it to the `examples` folder.
- Include a basic test file based on the with-emailpassword-vercel example.

**Comment by rishabhpoddar** [comment]
No need to create an issue for smaller PRs :). Normally, issues are only created where there will be multiple PRs associated with it. So closing this for now.

**Comment by rishabhpoddar** [comment]
No need to create an issue for smaller PRs :). Normally, issues are only created where there will be multiple PRs associated with it. So closing this for now.
