### ISSUE TITLE
Example Electron App out of date

### ISSUE THREAD

**Issue by mluogh** [supertokens/supertokens-auth-react#808]
I followed all the instructions given [here](https://github.com/supertokens/supertokens-auth-react/blob/dbbecb55fe5a06d275662f9d7d64c4fc5eca7d45/examples/with-thirdpartypasswordless-electron/README.md)

However, when I try to login using the Google auth, I get an error:

```
GET http://localhost:3000/auth/callback/google?state=eyJzdGF0ZSI6ImI5YTQwY2NmMDExODRiYzUyMTA2ZSJ9&code=4%2F0AeaYSHDygHXmetG6eUwQVrHXcy3ow3rKNUSXou_i-7Tpt1D98dJxAe0xm7GVE8cUUJVSaQ&scope=email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=none 
```

<img width="1470" alt="image" src="https://github.com/supertokens/supertokens-auth-react/assets/8098155/628d92b7-7ece-4261-8221-2a80be30bf1e">

My understanding is that the desired flow is Electron -> Google -> API Server (localhost:3001) --[Deeplink to Electron]--> Electron, but from the error, it seems like we get Electron -> Google -> localhost:3000 ?

**Comment by DBozhinovski** [comment]
I'm getting something similar, but not the same: 
![Screenshot from 2024-03-28 16-23-08](https://github.com/supertokens/supertokens-auth-react/assets/271746/09b6c803-f52a-4f07-9e67-123981b549e7)


In any case, the demo is not working as expected, so I'll take a look.
