### ISSUE TITLE
Create a theme attribute to the EmailPassword config

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#86]
Create a theme attribute to the EmailPassword config:

Contains:
 - palette
 - style
 - defaultToSignUp

For default theme, and same for custom themes in `supertokens-auth-react-themes`.

But if someone wants to implement their own theme, they can decide what goes in there.

```js
EmailPassword.init({
         theme: {
        palette: {
          colors
        },
        signInAndUpFeature: {
          signInForm: {
            style,
            ...anything
          }
        }
        
      },
   signInAndUpFeature: {
      ...
    }
})
```

**Comment by rishabhpoddar** [comment]
As discussed, we can do this at some point, however, it's not needed as of now.

**Comment by rishabhpoddar** [comment]
This is closed because this is irrelevant now.
