### ISSUE TITLE
Button clicked visual output

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#96]
We need to provide user feedback on button click on different forms

Related to https://github.com/supertokens/supertokens-auth-react/issues/45

**Comment by NkxxkN** [comment]
See https://material-ui.com/components/buttons/#button

Or Facebook login

**Comment by rishabhpoddar** [comment]
@mufassirkazi please have a look at this ans suggest what we should use for button click feedback

**Comment by mufassirkazi** [comment]
https://zpl.io/2y4k99p

I suggest we can use the styling inside the buttons under "Sizes" heading in the link given by kevin. The buttom named "Custom CSS" under "Customised buttons" also will work. The colors to be used are given in the zeplin link at the start of this comment.

**Comment by rishabhpoddar** [comment]
@NkxxkN I think we should do this soon. Having no feedback on button click is really odd.

**Comment by NkxxkN** [comment]
Sure. I prioritized it in https://github.com/supertokens/supertokens-core/projects/5
